SUBROUTINE LAPAP.VAL.BOLOSILLO.RT

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_System
    $INSERT I_F.VERSION
    $INSERT I_F.AC.LOCKED.EVENTS


    GOSUB LOAD
    GOSUB SELECT
    GOSUB PROCESS
*====
LOAD:
*====
    Y.ACCOUNT                = COMI
    Y.PARAMETER              = "BOLSILLO"

    FN.AC.LOCKED.EVENTS = 'F.AC.LOCKED.EVENTS'
    F.AC.LOCKED.EVENTS = ''
    CALL OPF(FN.AC.LOCKED.EVENTS,F.AC.LOCKED.EVENTS)
RETURN

*======
SELECT:
*======
    NO.OF.REC = ''; SEL.ERR = ''; Y.COUNT.LIST = ''; LIST.POS = '';
    SEL.CMD = "SELECT ":FN.AC.LOCKED.EVENTS:" WITH ACCOUNT.NUMBER EQ " :Y.ACCOUNT:" AND L.AC.LOCKE.TYPE EQ " :Y.PARAMETER;
    CALL EB.READLIST(SEL.CMD, SEL.LIST, "", NO.OF.REC, SEL.ERR);
    Y.COUNT.LOCK = DCOUNT(SEL.LIST,@FM);
RETURN

*=======
PROCESS:
*=======
    IF Y.COUNT.LOCK GE 3 THEN
        TEXT = "La cuenta numero: ":Y.ACCOUNT:" ya posee 3 bolsillos asociados"
        ETEXT = TEXT
        E = TEXT
        CALL ERR
    END

RETURN

END
