$PACKAGE APAP.LAPAP
SUBROUTINE L.APAP.COL.FF.EXTRACT.POST
*------------------------------------------------------------------------------
*---------------------------------------------------------------------------------------
*MODIFICATION HISTORY:
*DATE          WHO                 REFERENCE               DESCRIPTION
*13-07-2023    CONVERSION TOOL     R22 AUTO CONVERSION     TAM.BP is Removed
*13-07-2023    AJITHKUMAR S        R22 MANUAL CONVERSION   CALL RTN FORMAT CAN BE MODIFIED
*---------------------------------------------------------------------------------------	-
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.REDO.INTERFACE.PARAM ;*R22 Auto code conversion
    $INSERT I_L.APAP.COL.CUSTOMER.COMMON
    $INSERT I_F.TSA.SERVICE

    GOSUB INITIALISE

RETURN

INITIALISE:

*CALL L.APAP.COL.FF.EXTRACT.LOAD
    APAP.LAPAP.lApapColFfExtractLoad() ;*R22 MANUAL CODE CONVERSION

    Y.EXTRACT.OUT.PATH=R.REDO.INTERFACE.PARAM<REDO.INT.PARAM.FI.AUTO.PATH>
    LOOP
        REMOVE C.TABLE.ID FROM C.TABLES SETTING POS
    WHILE C.TABLE.ID:POS
        GOSUB TABLE.PROCESS
    REPEAT
    EXE.TOUCH='touch ':Y.EXTRACT.OUT.PATH:'/chk_file'
    SHELL.TCH ='SH -c '
    DAEMON.TCH = SHELL.TCH:EXE.TOUCH
    EXECUTE DAEMON.TCH RETURNING RETURN.VALUE CAPTURING CAPTURE.TCH.VALUE

    R.REDO.INTERFACE.PARAM<REDO.INT.PARAM.PAYMENT.REF> = 1
    CALL F.WRITE('F.REDO.INTERFACE.PARAM','COL001',R.REDO.INTERFACE.PARAM)
RETURN

TABLE.PROCESS:
    SHELL.CMD ='SH -c '
    EXEC.COM="cat "
    OLD.OUT.FILES = 'SESSION':C.TABLE.ID:'*'
    EXE.CAT = "cat ":Y.EXTRACT.OUT.PATH:"/":OLD.OUT.FILES:" >> ":Y.EXTRACT.OUT.PATH:"/":C.TABLE.ID:'.txt'
    EXE.RM="rm ":Y.EXTRACT.OUT.PATH:"/":OLD.OUT.FILES

    DAEMON.CMD = SHELL.CMD:EXE.CAT
    DAEMON.REM.CMD = SHELL.CMD:EXE.RM

    EXECUTE DAEMON.CMD RETURNING RETURN.VALUE CAPTURING CAPTURE.CAT.VALUE
    EXECUTE DAEMON.REM.CMD RETURNING RETURN.VALUE CAPTURING CAPTURE.REM.VALUE
RETURN
END
