* @ValidationCode : MjotMTk5NzcxNzU2MDpDcDEyNTI6MTcwMjk4ODM2MTU5MDpJVFNTMTotMTotMTowOjE6ZmFsc2U6Ti9BOlIyMl9TUDUuMDotMTotMQ==
* @ValidationInfo : Timestamp         : 19 Dec 2023 17:49:21
* @ValidationInfo : Encoding          : Cp1252
* @ValidationInfo : User Name         : ITSS1
* @ValidationInfo : Nb tests success  : N/A
* @ValidationInfo : Nb tests failure  : N/A
* @ValidationInfo : Rating            : N/A
* @ValidationInfo : Coverage          : N/A
* @ValidationInfo : Strict flag       : true
* @ValidationInfo : Bypass GateKeeper : false
* @ValidationInfo : Compiler Version  : R22_SP5.0
* @ValidationInfo : Copyright Temenos Headquarters SA 1993-2021. All rights reserved.
$PACKAGE APAP.LAPAP
SUBROUTINE L.APAP.TAKEOVER.LOAN
*------------------------------------------------------------------------
* Modification History :
*------------------------------------------------------------------------
*  DATE             WHO                   REFERENCE
* 21-APRIL-2023      Conversion Tool       R22 Auto Conversion  - F.READ to CACHE.READ and T24.BP is removed from Insert
* 13-APRIL-2023      Harsha                R22 Manual Conversion - No changes
* 08-12-2023         Suresh                Manual R22 conversion - OPF TO OPEN
* 18-12-2023         Santosh C             MANUAL R22 CODE CONVERSION   APAP Code Conversion Utility Check
*------------------------------------------------------------------------
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.USER
    $INSERT I_F.AA.ARRANGEMENT
    $INSERT I_F.AA.ARRANGEMENT.ACTIVITY
    $INSERT I_F.AA.TERM.AMOUNT
    $INSERT I_F.AA.PAYMENT.SCHEDULE
    $INSERT I_F.AA.ACCOUNT
    $USING EB.Interface ;*R22 Manual Code Conversion_Utility Check
   $USING EB.TransactionControl


    GOSUB  MAIN.PROCESS
RETURN

MAIN.PROCESS:
    GOSUB GET.LOADTABLE
    Y.ARCHIVO = 'CHANGECI009538'
    CALL F.READ(FN.SL,Y.ARCHIVO,Y.ID.LIST,F.SL,RET.ERR)
    LOOP
        REMOVE YGRP.ARR.ID FROM Y.ID.LIST SETTING YPOS
    WHILE YGRP.ARR.ID:YPOS
        Y.AA.ID = FIELD(YGRP.ARR.ID,',',1)
        Y.ORIG.CONTRACT.DATE = FIELD(YGRP.ARR.ID,',',2)
        Y.AMOUNT = FIELD(YGRP.ARR.ID,',',3)
        Y.OLD.ACCT = FIELD(YGRP.ARR.ID,',',4)
        Y.TOTALCOMIMENT1 = FIELD(YGRP.ARR.ID,',',5)
        GOSUB GET.ARRANGEMENT
        GOSUB SET.TOTALAMOUNT
        GOSUB SET.ACCOUNT
        GOSUB SET.ORIGINALDATE

    REPEAT

RETURN


GET.LOADTABLE:

    options = ''; OFS.REQ = ''; theResponse = ''
    options<1> = 'AA.COB'
    YVACIO = ''
    FN.AA.ARRANGEMENT = 'F.AA.ARRANGEMENT'
    F.AA.ARRANGEMENT = ''
    CALL OPF(FN.AA.ARRANGEMENT,F.AA.ARRANGEMENT)

    FN.USER = 'F.USER'
    F.USER = ''
    CALL OPF(FN.USER,F.USER)

    Y.USER = OPERATOR
    R.USER = ''
    CALL CACHE.READ(FN.USER, Y.USER, R.USER, USER.ERR)	;*R22 Auto Conversion  - F.READ to CACHE.READ
    Y.SIGN.ON.NAME = R.USER<EB.USE.SIGN.ON.NAME>
    Y.PASSWORD = R.USER<EB.USE.PASSWORD>
    FN.SL = '&SAVEDLISTS&'
    F.SL = ''
*   CALL OPF(FN.SL,F.SL)
    OPEN FN.SL TO F.SL ELSE   ;*R22 Manual Conversion
    END  ;*R22 Manual Conversion

RETURN

GET.ARRANGEMENT:
    R.ARRANGEMENT = '' ; ARR.ERR = '' ; Y.EFFECTIVE.DATE = TODAY
*    CALL F.READ(FN.AA.ARRANGEMENT,Y.AA.ID,R.ARRANGEMENT,F.AA.ARRANGEMENT,ARR.ERR)
    CALL F.READU(FN.AA.ARRANGEMENT,Y.AA.ID,R.ARRANGEMENT,F.AA.ARRANGEMENT,ARR.ERR,'');* R22 UTILITY AUTO CONVERSION
    Y.CUSTOMER = R.ARRANGEMENT<AA.ARR.CUSTOMER>
    Y.PRODUCT  = R.ARRANGEMENT<AA.ARR.PRODUCT>
    Y.CURRENCY = R.ARRANGEMENT<AA.ARR.CURRENCY>
    Y.CO.CODE = R.ARRANGEMENT<AA.ARR.CO.CODE>
    Y.START.DATE =  R.ARRANGEMENT<AA.ARR.START.DATE>
    Y.ALT.ID     = Y.OLD.ACCT
RETURN

SET.TOTALAMOUNT:
    Y.OFS.QUEUE = 'AA.ARRANGEMENT.ACTIVITY,AA.PRESTAMO/I/PROCESS,':Y.SIGN.ON.NAME:'/':Y.PASSWORD:'/':Y.CO.CODE:',,ARRANGEMENT:1:1=':Y.AA.ID:',ACTIVITY:1:1=LENDING-UPDATE-COMMITMENT,CUSTOMER:1:1=':Y.CUSTOMER:',PRODUCT:1:1=':Y.PRODUCT:',CURRENCY:1:1=':Y.CURRENCY:',EFFECTIVE.DATE:1:1=':Y.EFFECTIVE.DATE
    Y.OFS.QUEUE := ',PROPERTY:1:1=COMMITMENT,FIELD.NAME:1:1=AMOUNT:1:1,FIELD.VALUE:1:1=':Y.AMOUNT:','
    GOSUB PROCESS
    GOSUB SET.TOTALCOMIMENT
RETURN

SET.ACCOUNT:
    Y.ACTIVIDAD = 'LENDING-UPDATE-ACCOUNT'
    Y.OFS.QUEUE = "AA.ARRANGEMENT.ACTIVITY,AA.PRESTAMO/I/PROCESS//0/,":Y.SIGN.ON.NAME:"/":Y.PASSWORD:"/":Y.CO.CODE:",,ARRANGEMENT::=":Y.AA.ID:",ACTIVITY::=":Y.ACTIVIDAD:",CUSTOMER:1:1=":Y.CUSTOMER:",CURRENCY:1:1=":Y.CURRENCY:",PROPERTY:1:1=ACCOUNT,FIELD.NAME:1:1=ALT.ID:1:1,FIELD.NAME:1:2=ALT.ID:4:1,FIELD.VALUE:1:1=":YVACIO:",FIELD.VALUE:1:2=":Y.ALT.ID:",":
    GOSUB PROCESS
RETURN
SET.TOTALCOMIMENT:
    Y.TOTALCOMIMENT = Y.TOTALCOMIMENT1
    Y.OFS.QUEUE = 'AA.ARRANGEMENT.ACTIVITY,AA.PRESTAMO/I/PROCESS,':Y.SIGN.ON.NAME:'/':Y.PASSWORD:'/':Y.CO.CODE:',,ARRANGEMENT:1:1=':Y.AA.ID:',ACTIVITY:1:1=LENDING-ADJUST.BALANCE-MANT.SALD.CUOTA,CUSTOMER:1:1=':Y.CUSTOMER:',PRODUCT:1:1=':Y.PRODUCT:',CURRENCY:1:1=':Y.CURRENCY:',EFFECTIVE.DATE:1:1=':Y.EFFECTIVE.DATE
    Y.OFS.QUEUE := ',PROPERTY:1:1=MANT.SALD.CUOTA,FIELD.NAME:1:1=ADJ.BAL.AMT:2:2,FIELD.VALUE:1:1=':Y.TOTALCOMIMENT:','
    GOSUB PROCESS
    Y.TOTALCOMIMENT = '-':Y.AMOUNT
    Y.OFS.QUEUE = 'AA.ARRANGEMENT.ACTIVITY,AA.PRESTAMO/I/PROCESS,':Y.SIGN.ON.NAME:'/':Y.PASSWORD:'/':Y.CO.CODE:',,ARRANGEMENT:1:1=':Y.AA.ID:',ACTIVITY:1:1=LENDING-ADJUST.BALANCE-MANT.SALD.CUOTA,CUSTOMER:1:1=':Y.CUSTOMER:',PRODUCT:1:1=':Y.PRODUCT:',CURRENCY:1:1=':Y.CURRENCY:',EFFECTIVE.DATE:1:1=':Y.EFFECTIVE.DATE
    Y.OFS.QUEUE := ',PROPERTY:1:1=MANT.SALD.CUOTA,FIELD.NAME:1:1=ADJ.BAL.AMT:2:2,FIELD.VALUE:1:1=':Y.TOTALCOMIMENT:','
    GOSUB PROCESS
RETURN

SET.ORIGINALDATE:
    R.ARRANGEMENT<AA.ARR.ORIG.CONTRACT.DATE> = Y.ORIG.CONTRACT.DATE
    CALL F.WRITE(FN.AA.ARRANGEMENT,Y.AA.ID,R.ARRANGEMENT)
*    CALL JOURNAL.UPDATE('')
EB.TransactionControl.JournalUpdate('');* R22 UTILITY AUTO CONVERSION
RETURN

PROCESS:
    CRT "Processing string = ":Y.AA.ID
*   CALL OFS.CALL.BULK.MANAGER(options,Y.OFS.QUEUE,RESP,COMM)
    EB.Interface.OfsCallBulkManager(options,Y.OFS.QUEUE,RESP,COMM) ;*R22 Manual Code Conversion_Utility Check
    CRT "Response ":RESP
*    CALL JOURNAL.UPDATE('')
EB.TransactionControl.JournalUpdate('');* R22 UTILITY AUTO CONVERSION
RETURN
END
