* @ValidationCode : MjoxOTYxNzA4NjA4OkNwMTI1MjoxNjkwMTY3NTI4NzEwOklUU1MxOi0xOi0xOjA6MTpmYWxzZTpOL0E6UjIxX0FNUi4wOi0xOi0x
* @ValidationInfo : Timestamp         : 24 Jul 2023 08:28:48
* @ValidationInfo : Encoding          : Cp1252
* @ValidationInfo : User Name         : ITSS1
* @ValidationInfo : Nb tests success  : N/A
* @ValidationInfo : Nb tests failure  : N/A
* @ValidationInfo : Rating            : N/A
* @ValidationInfo : Coverage          : N/A
* @ValidationInfo : Strict flag       : true
* @ValidationInfo : Bypass GateKeeper : false
* @ValidationInfo : Compiler Version  : R21_AMR.0
* @ValidationInfo : Copyright Temenos Headquarters SA 1993-2021. All rights reserved.
$PACKAGE APAP.LAPAP
SUBROUTINE L.APAP.CRED.CAN.LOAND.LOAD
*-----------------------------------------------------------------------------
*MODIFICATION HISTORY:
*
* DATE              WHO                REFERENCE                 DESCRIPTION
* 13-07-2023     Conversion tool    R22 Auto conversion       FM TO @FM, VM to @VM, SM to @SM, F.READ to CACHE.READ
* 13-07-2023     Harishvikram C   Manual R22 conversion       No changes
*-----------------------------------------------------------------------------
    $INSERT I_COMMON                                   ;*R22 Auto conversion
    $INSERT I_EQUATE
    $INSERT I_F.AA.ARRANGEMENT
    $INSERT I_F.CUSTOMER
    $INSERT I_F.ACCOUNT
    $INSERT I_F.REDO.H.REPORTS.PARAM
    $INSERT I_F.DATES
    $INSERT I_L.APAP.CRED.CAN.LOAND.COMMON ;* R22 Manual R22 conversion
    $INSERT I_F.AA.ACTIVITY.HISTORY
    $INSERT I_F.AA.OVERDUE
    $INSERT I_F.AA.ACCOUNT
    $INSERT I_F.AA.ARRANGEMENT.ACTIVITY
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.TELLER
    $INSERT I_F.REDO.APAP.CREDIT.CARD.DET
    $INSERT I_F.AA.LIMIT
    $INSERT I_F.AA.INTEREST
    $INSERT I_F.AA.TERM.AMOUNT
    $INSERT I_F.AA.ACCOUNT.DETAILS
    $INSERT I_F.AA.PAYMENT.SCHEDULE
    $INSERT I_F.AA.INTEREST.ACCRUALS
    $INSERT I_F.AA.CUSTOMER
    $INSERT I_F.EB.CONTRACT.BALANCES
    $INSERT I_F.ST.LAPAP.REPORTDE16                      ;*R22 Auto conversion

    GOSUB MAIN.PROCESO

MAIN.PROCESO:
    GOSUB GET.LOARD.TABLE
    GOSUB GET.CONSTANTE.VAR
    GOSUB GET.CAMPOS.LOCALES
RETURN
GET.LOARD.TABLE:
*****************
    FN.AA.ARRANGEMENT = "F.AA.ARRANGEMENT"; F.AA.ARRANGEMENT  = ""
    CALL OPF(FN.AA.ARRANGEMENT,F.AA.ARRANGEMENT)

    FN.ACCOUNT = "F.ACCOUNT"; F.ACCOUNT = ''
    CALL OPF(FN.ACCOUNT,F.ACCOUNT)

    FN.CUSTOMER = "F.CUSTOMER"; F.CUSTOMER = ''
    CALL OPF(FN.CUSTOMER,F.CUSTOMER)

    FN.REDO.H.REPORTS.PARAM = "F.REDO.H.REPORTS.PARAM"
    F.REDO.H.REPORTS.PARAM  = ""
    CALL OPF(FN.REDO.H.REPORTS.PARAM,F.REDO.H.REPORTS.PARAM)

    FN.AA.ACTIVITY.HISTORY = "F.AA.ACTIVITY.HISTORY"; F.AA.ACTIVITY.HISTORY  = ""
    CALL OPF(FN.AA.ACTIVITY.HISTORY,F.AA.ACTIVITY.HISTORY)

    FN.AA.ARRANGEMENT.ACTIVITY = "F.AA.ARRANGEMENT.ACTIVITY"; F.AA.ARRANGEMENT.ACTIVITY = ''
    CALL OPF(FN.AA.ARRANGEMENT.ACTIVITY,F.AA.ARRANGEMENT.ACTIVITY)

    FN.DATES = 'F.DATES'; F.DATES = ''
    CALL OPF(FN.DATES,F.DATES)

    FN.FUNDS.TRANSFER.HST = 'F.FUNDS.TRANSFER$HIS' ; F.FUNDS.TRANSFER.HST = ''
    CALL OPF(FN.FUNDS.TRANSFER.HST,F.FUNDS.TRANSFER.HST)

    FN.TELLERHIS = "F.TELLER$HIS" ; F.TELLERHIS = ''
    CALL OPF(FN.TELLERHIS,F.TELLERHIS)

    FN.REDO.APAP.CREDIT.CARD.DET = 'F.REDO.APAP.CREDIT.CARD.DET'; F.REDO.APAP.CREDIT.CARD.DET = ''
    CALL OPF(FN.REDO.APAP.CREDIT.CARD.DET,F.REDO.APAP.CREDIT.CARD.DET)

    FN.ACCOUNT.HST = 'F.ACCOUNT$HIS'
    F.ACCOUNT.HST = ''
    CALL OPF(FN.ACCOUNT.HST,F.ACCOUNT.HST)

    FN.EB.CONT.BAL = "F.EB.CONTRACT.BALANCES"
    F.EB.CONT.BAL = ""
    CALL OPF(FN.EB.CONT.BAL,F.EB.CONT.BAL)

    FN.LIMIT = "F.LIMIT"
    F.LIMIT  = ""
    CALL OPF(FN.LIMIT,F.LIMIT)

    FN.AA.LIMIT = 'F.AA.ARR.LIMIT'
    F.AA.LIMIT = ''
    R.AA.LIMIT = ''
    CALL OPF(FN.AA.LIMIT,F.AA.LIMIT)

    FN.AA.ARRANGEMENT = "F.AA.ARRANGEMENT"
    F.AA.ARRANGEMENT  = ""
    CALL OPF(FN.AA.ARRANGEMENT,F.AA.ARRANGEMENT)

    FN.AA.ARR.TERM.AMOUNT = "F.AA.ARR.TERM.AMOUNT"
    F.AA.ARR.TERM.AMOUNT  = ""
    CALL OPF(FN.AA.ARR.TERM.AMOUNT,F.AA.ARR.TERM.AMOUNT)

    FN.AA.PRODUCT.GROUP = "F.AA.PRODUCT.GROUP"
    F.AA.PRODUCT.GROUP  = ""
    CALL OPF(FN.AA.PRODUCT.GROUP,F.AA.PRODUCT.GROUP)

    FN.LAPAP.REPORTDE16 = "F.ST.LAPAP.REPORTDE16"
    F.LAPAP.REPORTDE16 = ''
    CALL OPF(FN.LAPAP.REPORTDE16,F.LAPAP.REPORTDE16)

RETURN

GET.CONSTANTE.VAR:
    Y.APAP.REP.PARAM.ID = 'REDO.DE16'
    CALL CACHE.READ(FN.REDO.H.REPORTS.PARAM,Y.APAP.REP.PARAM.ID,R.REDO.H.REPORTS.PARAM,REDO.H.REPORTS.PARAM.ERR)
    IF R.REDO.H.REPORTS.PARAM THEN
        Y.OUTPUT.DIR = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.OUT.DIR>
        Y.FILE.NAME  = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.OUT.FILE.NAME>
        Y.FILE.DIR   = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.TEMP.DIR>
        Y.FIELD.NME.ARR = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.FIELD.NAME>
        Y.FIELD.VAL.ARR = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.FIELD.VALUE>
        Y.DISP.TEXT.ARR = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.DISPLAY.TEXT>
    END
    CHANGE @VM TO @FM IN Y.FIELD.NME.ARR
    CHANGE @SM TO @FM IN Y.FIELD.NME.ARR
    CHANGE @VM TO @FM IN Y.FIELD.VAL.ARR
    CHANGE @SM TO @FM IN Y.FIELD.VAL.ARR
    CHANGE @VM TO @FM IN Y.DISP.TEXT.ARR
    CHANGE @SM TO @FM IN Y.DISP.TEXT.ARR

    LOCATE "RP.PAYOFF.CHQ" IN Y.FIELD.VAL.ARR<1> SETTING EYPO.POS THEN
        Y.RP.PAYOFF.CHQ =  Y.DISP.TEXT.ARR<EYPO.POS,1>
    END
    LOCATE "RP.PAYOFF" IN Y.FIELD.VAL.ARR<1> SETTING EYPO.POS THEN
        Y.RP.PAYOFF =  Y.DISP.TEXT.ARR<EYPO.POS,1>
    END
    R.FECHAS = ''; ERR.FECHAS = ''
*    CALL CACHE.READ(FN.DATES, 'DO0010001', R.FECHAS, ERR.FECHAS)          ;*R22 Auto conversion
IDVAR.1 = 'DO0010001' ;* R22 UTILITY AUTO CONVERSION
    CALL CACHE.READ(FN.DATES, IDVAR.1, R.FECHAS, ERR.FECHAS)          ;*R22 Auto conversion;* R22 UTILITY AUTO CONVERSION
    Y.FECHA.CORTE = R.FECHAS<EB.DAT.LAST.WORKING.DAY>
    Y.FECHA1 = Y.FECHA.CORTE[1,6]
    Y.FECHA2 = '01'
    Y.FECHA.INICIO = Y.FECHA1:"":Y.FECHA2
RETURN
*------------------
GET.CAMPOS.LOCALES:
*------------------
    Y.APPL = "AA.PRD.DES.ACCOUNT":@FM:"AA.PRD.DES.OVERDUE":@FM:"CUSTOMER"
    Y.FLD  = "L.CR.FACILITY":@FM:"L.LOAN.STATUS.1":@VM:"L.LOAN.COND":@FM:"L.CU.DEBTOR"
    Y.POS  = ""
    CALL MULTI.GET.LOC.REF(Y.APPL,Y.FLD,Y.POS)
    Y.L.CR.FACILITY.POS = Y.POS<1,1>
    Y.L.LOAN.STATUS.1.POS = Y.POS<2,1>
    Y.L.LOAN.COND.POST = Y.POS<2,2>
    L.CU.DEBTOR.POS = Y.POS<3,1>
RETURN
END
