*----------------------------------------------------------------------------------------------------------
* <Rating>-10</Rating>
*--------------------------------------------------------------------------------------------------------
SUBROUTINE REDO.ACCT.DEP.DETAILS.LOAD
$INSERT I_COMMON
$INSERT I_EQUATE
$INSERT I_F.ACCOUNT
$INSERT I_F.CUSTOMER
$INSERT I_F.STMT.ENTRY
$INSERT I_F.RELATION
$INSERT I_F.CATEGORY
$INSERT I_ENQUIRY.COMMON
$INSERT I_F.ACCOUNT.CLASS
$INSERT I_F.REDO.AML.PARAM
$INSERT I_REDO.ACCT.DEP.DETAILS.COMMON
$INSERT I_F.REDO.H.TELLER.TXN.CODES
$INSERT I_F.REDO.H.REPORTS.PARAM
$INSERT I_F.COMPANY
$INSERT I_F.MNEMONIC.COMPANY

GOSUB INIT
*
RETURN
*--------------------------------------------------------------------------------------------------------------------------------------------
*****
INIT:
*****
FN.ACCOUNT = 'F.ACCOUNT'
F.ACCOUNT = ''
CALL OPF(FN.ACCOUNT,F.ACCOUNT)

FN.REDO.AML.PARAM = 'F.REDO.AML.PARAM'
F.REDO.AML.PARAM = ''
R.REDO.AML.PARAM = ''
CALL CACHE.READ(FN.REDO.AML.PARAM,'SYSTEM',R.REDO.AML.PARAM,ERR.RAP)

FN.CUSTOMER = 'F.CUSTOMER'
F.CUSTOMER = ''
CALL OPF(FN.CUSTOMER,F.CUSTOMER)

FN.STMT.ENTRY = 'F.STMT.ENTRY'
F.STMT.ENTRY = ''
CALL OPF(FN.STMT.ENTRY,F.STMT.ENTRY)

FN.RELATION = 'F.RELATION'
F.RELATION = ''
CALL OPF(FN.RELATION,F.RELATION)

FN.CATEGORY = "F.CATEGORY"
F.CATEGORY = ""
CALL OPF(FN.CATEGORY,F.CATEGORY)

FN.REDO.H.REPORTS.PARAM = "F.REDO.H.REPORTS.PARAM"
F.REDO.H.REPORTS.PARAM = ""
CALL OPF(FN.REDO.H.REPORTS.PARAM,F.REDO.H.REPORTS.PARAM)

FN.ACCOUNT.CLASS = "F.ACCOUNT.CLASS"
F.ACCOUNT.CLASS = ""
CALL OPF(FN.ACCOUNT.CLASS,F.ACCOUNT.CLASS)

FN.REDO.H.TELLER.TXN.CODES = "F.REDO.H.TELLER.TXN.CODES"
F.REDO.H.TELLER.TXN.CODES = ""
CALL OPF(FN.REDO.H.TELLER.TXN.CODES,F.REDO.H.TELLER.TXN.CODES)

FN.REDO.APAP.BKP.REP55 = "F.REDO.APAP.BKP.REP55"
F.REDO.APAP.BKP.REP55 = ""
CALL OPF(FN.REDO.APAP.BKP.REP55,F.REDO.APAP.BKP.REP55)

FN.COMPANY = "F.COMPANY"
F.COMPANY = ""
CALL OPF(FN.COMPANY,F.COMPANY)

FN.MNEMONIC.COMPANY = "F.MNEMONIC.COMPANY"
F.MNEMONIC.COMPANY = ""
CALL OPF(FN.MNEMONIC.COMPANY,F.MNEMONIC.COMPANY)

FN.ACCT.ENT.LWORK.DAY = "F.ACCT.ENT.LWORK.DAY"
F.ACCT.ENT.LWORK.DAY = ""
CALL OPF(FN.ACCT.ENT.LWORK.DAY,F.ACCT.ENT.LWORK.DAY)
*
Y.AGENCY = ''
Y.DATE = ''
Y.TRANS.REF = ''
Y.INPUTTER = ''
Y.AUTHORISER = ''
Y.AC.CATEGORY = ''
Y.AC.CURRENCY = ''
Y.CUSTOMER = ''
Y.ACCOUNT.OFFICER = ''
Y.TRANS.AMOUNT = ''
Y.ACCOUNT.NAME = ''
Y.SELECTION.VALUE = ''
Y.RETURN = ''
Y.RETURN.DATA = ''
Y.ACCOUNT.TYPE = ''
Y.CURRENCY = ''
Y.EX.AGENCY = ''
Y.TRANSACTION.DATE = ''
*
CALL F.READ(FN.REDO.H.REPORTS.PARAM,"REP55",R.REDO.H.REPORTS.PARAM,F.REDO.H.REPORTS.PARAM,REPORTS.PARAM.ERR)
Y.OUT.PATH = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.OUT.DIR>

FN.OUT.PATH = Y.OUT.PATH
F.OUT.PATH = ""
CALL OPF(FN.OUT.PATH,F.OUT.PATH)

R.REDO.AML.PARAM = ''
ERR.RAP = ''
CALL CACHE.READ(FN.REDO.AML.PARAM,'SYSTEM',R.REDO.AML.PARAM,ERR.RAP)
Y.AMT = R.REDO.AML.PARAM<AML.PARAM.AMT.LIMIT.LCY>

LOC.L.CU.TIPO.CL.POS = ''
CALL GET.LOC.REF('CUSTOMER','L.CU.TIPO.CL',LOC.L.CU.TIPO.CL.POS)

CALL F.READ(FN.ACCOUNT.CLASS,"SAVINGS",R.ACCOUNT.CLASS,F.ACCOUNT.CLASS,AC.CLASS.ERR)
Y.SAVE.CAT = R.ACCOUNT.CLASS<AC.CLS.CATEGORY>
CHANGE VM TO FM IN Y.SAVE.CAT

*Tus Start
* CALL F.READ(FN.REDO.H.TELLER.TXN.CODES,"SYSTEM",R.REDO.H.TELLER.TXN.CODES,F.REDO.H.TELLER.TXN.CODES,TXN.CODES.ERR) 
CALL CACHE.READ(FN.REDO.H.TELLER.TXN.CODES,"SYSTEM",R.REDO.H.TELLER.TXN.CODES,TXN.CODES.ERR) 
* Tus End
Y.CUR.CAT = R.REDO.H.TELLER.TXN.CODES<TT.TXN.CURR.ACC.CATEG>
CHANGE VM TO FM IN Y.CUR.CAT

Y.TOTAL.CAT = Y.SAVE.CAT:FM:Y.CUR.CAT
*
RETURN
*--------------------------------------------------------------------------------------------------------
END
