*-----------------------------------------------------------------------------
* <Rating>-20</Rating>
*-----------------------------------------------------------------------------
  SUBROUTINE REDO.VAL.FILL.LETTER.DET
*-----------------------------------------------------------------------------
* Company Name : ASOCIACION POPULAR DE AHORROS Y PRESTAMOS
* Developed By : Prabhu N
* Program Name : REDO.V.ACH.POP.DETAILS
*-----------------------------------------------------------------------------
* Description :
* Linked with :
* In Parameter : ENQ.DATA
* Out Parameter : None
*
**DATE           ODR                   DEVELOPER               VERSION
*
*21/09/11      PACS00106561           PRABHU N                   MODIFICATION
*-----------------------------------------------------------------------------

$INSERT I_COMMON
$INSERT I_EQUATE
$INSERT I_F.BENEFICIARY
$INSERT I_System
$INSERT I_F.FUNDS.TRANSFER
$INSERT I_F.FT.COMMISSION.TYPE
$INSERT I_F.AI.REDO.ARCIB.PARAMETER


  GOSUB OPEN.FILES
  GOSUB FILL.DETAILS.FT
  RETURN
*-----------*
OPEN.FILES:
*-----------*

  GET.ARC.CHG.CODE = ''
  Y.CHARGE.KEY = ''
  FN.ARCIB.PARAM='F.AI.REDO.ARCIB.PARAMETER'
  F.ARCIB.PARAM=''
  *CALL OPF(FN.ARCIB.PARAM,F.ARCIB.PARAM) ;*Tus S/E

  FN.FT.COMMISSION.TYPE='F.FT.COMMISSION.TYPE'
  F.FT.COMMISSION.TYPE=''
  CALL OPF(FN.FT.COMMISSION.TYPE,F.FT.COMMISSION.TYPE)
  GET.ARC.CHG.CODE = System.getVariable("CURRENT.ARC.CHG.CODE")

  RETURN

*------------*
FILL.DETAILS.FT:
*------------*
  CALL CACHE.READ(FN.ARCIB.PARAM,'SYSTEM',R.ARC.REC,ARC.ERR)
  IF NOT(ARC.ERR) THEN
    Y.CHARGE.KEY = GET.ARC.CHG.CODE
  END

  CALL F.READ(FN.FT.COMMISSION.TYPE,Y.CHARGE.KEY,R.FT.COMMISSION.TYPE,F.FT.COMMISSION.TYPE,COMM.TYPE.ERR)
  Y.DEFAULT.CCY=R.FT.COMMISSION.TYPE<FT4.DEFAULT.CCY>
  Y.CURRENCY=R.FT.COMMISSION.TYPE<FT4.CURRENCY>
  IF Y.DEFAULT.CCY NE '' THEN
    R.NEW(FT.DEBIT.CURRENCY)=Y.DEFAULT.CCY
    LOCATE Y.DEFAULT.CCY IN Y.CURRENCY<1,1> SETTING POS1 THEN
      R.NEW(FT.DEBIT.AMOUNT)=R.FT.COMMISSION.TYPE<FT4.FLAT.AMT,POS1>
      R.NEW(FT.CREDIT.ACCT.NO)="PL":R.FT.COMMISSION.TYPE<FT4.CATEGORY.ACCOUNT>
    END
  END ELSE
    LOCATE LCCY IN Y.CURRENCY<1,1> SETTING POS1 THEN
      R.NEW(FT.DEBIT.AMOUNT)=R.FT.COMMISSION.TYPE<FT4.FLAT.AMT,POS1>
    END
    R.NEW(FT.CREDIT.ACCT.NO)="PL":R.FT.COMMISSION.TYPE<FT4.CATEGORY.ACCOUNT>
  END


  RETURN

END
