*-----------------------------------------------------------------------------
* <Rating>-10</Rating>
*-----------------------------------------------------------------------------
* COMPANY NAME: ASOCIACION POPULAR DE AHORROS Y PRESTAMOS
* DEVELOPED BY: PRABHU N
* PROGRAM NAME: REDO.VAL.STO.LOC.REF
* ODR NO      :PACS00125978
*----------------------------------------------------------------------
  SUBROUTINE REDO.VAL.STO.DUP.LOC.REF
$INSERT I_COMMON
$INSERT I_EQUATE
$INSERT I_F.STANDING.ORDER
$INSERT I_F.REDO.APAP.STO.DUPLICATE

  GOSUB INIT

  RETURN

*****
INIT:
****

  START.DATE = COMI

  IF START.DATE LE TODAY THEN
    AF = REDO.SO.STO.START.DATE
    ETEXT = 'EB-DATE.G..TODAY'
    CALL STORE.END.ERROR

  END

  START.DAY=START.DATE[7,2]
  FREQ.MTH='M01'
  END.DATE=R.NEW(REDO.SO.CURRENT.END.DATE)

  IN.FREQ=START.DATE:FREQ.MTH:START.DAY
  CALL EB.CONVERT.FQU.FORMAT(IN.FREQ,OUT.FREQ,ERR.MSG)
  R.NEW(REDO.SO.CURRENT.FREQUENCY)=OUT.FREQ
  RETURN
END
