*-----------------------------------------------------------------------------
* <Rating>-2</Rating>
*-----------------------------------------------------------------------------
  SUBROUTINE REDO.STO.NCF(FT.ID,R.FT)

$INSERT I_COMMON
$INSERT I_EQUATE
$INSERT I_GTS.COMMON
$INSERT I_System
$INSERT I_F.TELLER
$INSERT I_F.FUNDS.TRANSFER
$INSERT I_F.TELLER.TRANSACTION
$INSERT I_F.FT.COMMISSION.TYPE
$INSERT I_F.FT.TXN.TYPE.CONDITION

  FN.FT = 'F.FUNDS.TRANSFER'
  F.FT = ''
  CALL OPF(FN.FT,F.FT)

*    CALL F.READ(FN.FT,FT.ID,R.FT,F.FT,E.FT)
  MATPARSE R.NEW FROM R.FT

  Y.V$FUNCTION = V$FUNCTION
  V$FUNCTION = 'I'
  CALL REDO.V.CHK.TAX.CHRG
  CALL REDO.ARC.FT.CALC.COMM
  CALL REDO.V.FT.AUTH.UPD.NCF
  CALL REDO.V.AUTH.FT.WV.COMTAX
  V$FUNCTION = Y.V$FUNCTION
*    MATBUILD R.FT FROM R.NEW
  CALL F.MATWRITE(FN.FT,FT.ID,MAT R.NEW,STD.ORDER.REC.SIZE)

  RETURN
END
