* I_F.REDO.VISION.PLUS.WS Created 30 OCT 23 at 05:28AM by t24dev9/SJIJON.02
*      PREFIX[AP.VP]
                  EQU AP.VP.NUM.TARJETA TO 1,   RedoVisionPlusWs_NumTarjeta TO 1,
                            AP.VP.CANAL TO 2,   RedoVisionPlusWs_Canal TO 2,
                           AP.VP.MONEDA TO 3,   RedoVisionPlusWs_Moneda TO 3,
                              AP.VP.MES TO 4,   RedoVisionPlusWs_Mes TO 4,
                              AP.VP.ANO TO 5,   RedoVisionPlusWs_Ano TO 5,
                       AP.VP.RESERVED.2 TO 6,   RedoVisionPlusWs_Reserved2 TO 6,
                       AP.VP.RESERVED.1 TO 7,   RedoVisionPlusWs_Reserved1 TO 7
