* I_F.REDO.PADRON.WS Created 24 OCT 23 at 12:17PM by t24dev9/SJIJON.02
*      PREFIX[PAD.WS]
                       EQU PAD.WS.CEDULA TO 1,   RedoPadronWs_Cedula TO 1,
                       PAD.WS.RESERVED.5 TO 2,   RedoPadronWs_Reserved5 TO 2,
                       PAD.WS.RESERVED.4 TO 3,   RedoPadronWs_Reserved4 TO 3,
                       PAD.WS.RESERVED.3 TO 4,   RedoPadronWs_Reserved3 TO 4,
                       PAD.WS.RESERVED.2 TO 5,   RedoPadronWs_Reserved2 TO 5,
                       PAD.WS.RESERVED.1 TO 6,   RedoPadronWs_Reserved1 TO 6
