SUBROUTINE L.APAP.VAL.JSON.OUT

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.L.APAP.JSON.TO.OFS

    GOSUB PROCESS
RETURN

PROCESS:
*----------

    IF R.NEW(ST.JSON.OPERATION.TYPE) EQ "OUT" AND  R.NEW(ST.JSON.OBJECT) NE "NONE" THEN
        TEXT="L.APAP.OUT.JSON"
        CURR.NO=1
        CALL STORE.OVERRIDE(CURR.NO)
        RETURN
    END
RETURN
END
