SUBROUTINE L.APAP.COMPRA.PAS.ACT.SELECT
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.ACCOUNT
    $INSERT I_F.AZ.ACCOUNT
    $INSERT I_F.CUSTOMER
    $INSERT I_BATCH.FILES
    $INSERT L.APAP.COMPRA.PAS.ACT.COMMON
    $INSERT I_F.DATES
    $INSERT I_F.BASIC.INTEREST
    $INSERT I_F.ACCOUNT.CREDIT.INT
    $INSERT I_F.GROUP.CREDIT.INT
    SEL.CMD = " SELECT " : FN.CUS
    CALL EB.READLIST(SEL.CMD, SEL.LIST,'',NO.OF.RECS,SEL.ERR)
    CALL BATCH.BUILD.LIST('',SEL.LIST)
RETURN
END
