SUBROUTINE LAPAP.OFS.INTEREST.PAID.SELECT

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.DATES
    $INSERT I_F.ACCOUNT
    $INSERT I_F.AZ.ACCOUNT
    $INSERT I_F.STMT.ACCT.CR

    $INSERT I_LAPAP.OFS.INTEREST.PAID.COMMON

    SEL.CMD.AZ = "SELECT FBNK.AZ.ACCOUNT"
    CALL EB.READLIST(SEL.CMD.AZ,SEL.LIST.AZ,'',NO.OF.RECS,SEL.ERR.AZ)

    CALL BATCH.BUILD.LIST('',SEL.LIST.AZ)
*CALL LAPAP.OFS.INTEREST.PAID(SEL.LIST.AZ)

RETURN

END
