SUBROUTINE LAPAP.PURGAL.OFSREQUESTD(PURGA.ID)
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.REDO.H.CUSTOMER.PROVISIONING
    $INSERT I_LAPAP.PURGAL.OFSREQUESTD.COMMON
    $INSERT I_F.OFS.REQUEST.DETAIL

    CALL F.DELETE(FN.REQ.PURGA,PURGA.ID)

END
