* @ValidationCode : MjotNDc5MjAzMzg0OlVURi04OjE2ODkzMjk1MTI3MDg6QWRtaW46LTE6LTE6MDowOmZhbHNlOk4vQTpSMjFfQU1SLjA6LTE6LTE=
* @ValidationInfo : Timestamp         : 14 Jul 2023 15:41:52
* @ValidationInfo : Encoding          : UTF-8
* @ValidationInfo : User Name         : Admin
* @ValidationInfo : Nb tests success  : N/A
* @ValidationInfo : Nb tests failure  : N/A
* @ValidationInfo : Rating            : N/A
* @ValidationInfo : Coverage          : N/A
* @ValidationInfo : Strict flag       : N/A
* @ValidationInfo : Bypass GateKeeper : false
* @ValidationInfo : Compiler Version  : R21_AMR.0
* @ValidationInfo : Copyright Temenos Headquarters SA 1993-2021. All rights reserved.
$PACKAGE APAP.LAPAP
SUBROUTINE LAPAP.PROCES.RN.RT(Y.AAA.ID)
*--------------------------------------------------------------------------------------------------
* Description           : Rutina MAIN para el proceso de actualizacion RN o RT
* Developed On          : 23-10-2021
* Developed By          : APAP
* Development Reference : ET-5416
*--------------------------------------------------------------------------------------------------
*-----------------------------------------------------------------------------
* Modification History
* DATE               AUTHOR              REFERENCE              DESCRIPTION
* 14-07-2023    Conversion Tool        R22 Auto Conversion     BP is removed in insert file,SM to @SM,FM to @FM,VM to @VM
* 14-07-2023    Narmadha V             R22 Manual Conversion   Call routine format modified
*-----------------------------------------------------------------------------
    $INSERT I_COMMON ;*R22 Auto Conversion - START
    $INSERT I_EQUATE
    $INSERT I_BATCH.FILES
    $INSERT I_TSA.COMMON
    $INSERT I_F.AA.ARRANGEMENT.ACTIVITY
    $INSERT I_F.AA.OVERDUE
    $INSERT I_F.AA.ARRANGEMENT
*   $INSERT I_F.AA.OVERDUE
    $INSERT I_LAPAP.PROCES.RN.RT.COMMON
    $INSERT I_F.AA.CUSTOMER
    $INSERT I_F.REDO.CAMPAIGN.TYPES ;*R22 Auto Conversion -END
    $USING APAP.AA


    GOSUB PROCESO.MAIN


RETURN

PROCESO.MAIN:
    GOSUB LEER.ACTIVIDA.AAA
    GOSUB LEER.CONCATE.TABLE
    IF R.LAPAP.CONCATE.RN.RT THEN
        RETURN
    END
    GOSUB LEER.ARRANGEMENT

    IF Y.ARR.STATUS EQ 'CURRENT' THEN
        OUT.RECORD = '';
        APAP.AA.redoBConLnsByDebtorAaRecs(Y.ARRANGEMENT.ID,OUT.RECORD);*R22 Manual Conversion
        R.AA.OVERDUE.APP = FIELD(OUT.RECORD,"*",5)
        R.AA.CUSTOMER = FIELD(OUT.RECORD,"*",9)
        YL.AA.CAMP.TY = R.AA.CUSTOMER<AA.CUS.LOCAL.REF,L.AA.CAMP.TY.POS>
        GOSUB GET.TIPO.CAMPANA

        IF Y.L.LOAN.COND.T NE 'RN' AND Y.L.LOAN.COND.T NE 'RT' AND Y.L.LOAN.COND.T NE 'Restructured' THEN
            RETURN
        END

        GOSUB GET.OVERDUE
        IF Y.ACTUALIZAR.RT.RN EQ 'YES' THEN
            Y.CONDICION = CHANGE(Y.CONDICION,@SM,@FM)
            Y.CONDICION = CHANGE(Y.CONDICION,@VM,@FM)
            IF Y.L.LOAN.COND.T EQ 'RN' OR Y.L.LOAN.COND.T EQ 'Restructured' THEN
                GOSUB CREAR.REGISTRO.INFILE.RN
                RETURN
            END
            IF Y.L.LOAN.COND.T EQ 'RT' THEN
                GOSUB CREAR.REGISTRO.INFINE.RT
                RETURN
            END
        END
    END
RETURN


LEER.ACTIVIDA.AAA:

    R.AA.ARRANGEMENT.ACTIVITY = ''; AAA.ERROR = ''; Y.ARRANGEMENT.ID = '';
    CALL F.READ(FN.AA.ARRANGEMENT.ACTIVITY,Y.AAA.ID,R.AA.ARRANGEMENT.ACTIVITY,FV.AA.ARRANGEMENT.ACTIVITY,AAA.ERROR)
    Y.ARRANGEMENT.ID = R.AA.ARRANGEMENT.ACTIVITY<AA.ARR.ACT.ARRANGEMENT>
RETURN

LEER.CONCATE.TABLE:

    R.LAPAP.CONCATE.RN.RT = ''; ERRR.CONCATE = '';
    CALL F.READ(FN.LAPAP.CONCATE.RN.RT,Y.ARRANGEMENT.ID,R.LAPAP.CONCATE.RN.RT,FV.LAPAP.CONCATE.RN.RT,ERRR.CONCATE)
RETURN


LEER.ARRANGEMENT:

    R.ARRANGEMENT = ''; AA.ERROR = ''; Y.PRESTAMO.ID = ''; Y.ARR.STATUS = '';
    CALL F.READ (FN.AA.ARRANGEMENT,Y.ARRANGEMENT.ID,R.ARRANGEMENT,FV.AA.ARRANGEMENT,AA.ERROR)
    Y.ARR.STATUS = R.ARRANGEMENT<AA.ARR.ARR.STATUS>
    Y.PRESTAMO.ID = R.ARRANGEMENT<AA.ARR.LINKED.APPL.ID,1>
RETURN

GET.OVERDUE:

    Y.ACTUALIZAR.RT.RN = '';
    Y.ESTADO.ACTUAL = R.AA.OVERDUE.APP<AA.OD.LOCAL.REF,L.LOAN.STATUS.1.POS>
    Y.FECHA.CASTIGO = R.AA.OVERDUE.APP<AA.OD.LOCAL.REF,L.STATUS.CHG.DT.POS>
    Y.CONDICION = R.AA.OVERDUE.APP<AA.OD.LOCAL.REF,L.LOAN.COND.POS>
    LOCATE "RN" IN Y.CONDICION<1,1> SETTING COD.POS1 THEN
        Y.ACTUALIZAR.RT.RN = 'NO';
        RETURN
    END

    LOCATE "RT" IN Y.CONDICION<1,1> SETTING COD.POS2 THEN
        Y.ACTUALIZAR.RT.RN = 'NO';
        RETURN
    END

    LOCATE "Restructured" IN Y.CONDICION<1,1> SETTING COD.POS2 THEN
        Y.ACTUALIZAR.RT.RN = 'NO';
        RETURN
    END


    Y.ACTUALIZAR.RT.RN = 'YES';

RETURN

GET.TIPO.CAMPANA:

    SEL.CMD.IN =  "SELECT ":FN.REDO.CAMPAIGN.TYPES:" L.LOAN.COND WITH @ID EQ ":YL.AA.CAMP.TY
    CALL EB.READLIST(SEL.CMD.IN, SEL.LIST.IN, '',NO.OF.RECS.IN,SEL.ERR.IN)

    LOOP
        REMOVE Y.ID.RECORD FROM SEL.LIST.IN SETTING REGISTRO.POS.IN
    WHILE Y.ID.RECORD  DO
        Y.L.LOAN.COND.T = Y.ID.RECORD

    REPEAT

RETURN


CREAR.REGISTRO.INFILE.RN:

    Y.ACTIVIDAD = "LENDING-UPDATE-APAP.OVERDUE"
    Y.PROPERTY = "APAP.OVERDUE"
    Y.COMPO.STATUS = "L.LOAN.STATUS.1"
    Y.CAMPO.FECHA.CAMBIO.STATUS = "L.STATUS.CHG.DT"
    Y.CAMPO.TIPO.RECTRUCTURADO = "L.RESTRUCT.TYPE"
    Y.CAMPO.COND = "L.LOAN.COND"
    Y.FILE.FINAL = "AA.LIST.UPD"
    Y.CONT.COND = DCOUNT(Y.CONDICION,@FM)
    Y.NUM.COND = Y.CONT.COND + 1;
    Y.FIELD.CAMPO.RESTRUCT.TYPE = "L.RESTRUCT.TYPE:1"
    Y.FIELD.ESTATUS = Y.COMPO.STATUS:":":"1"
    Y.FIELD.FECHA.STATU = Y.CAMPO.FECHA.CAMBIO.STATUS:":":"1"
    Y.FIELD.COND = Y.CAMPO.COND:":":Y.NUM.COND
    R.LAPAP.CONCATE.RN.RT = Y.ARRANGEMENT.ID:"|":Y.ACTIVIDAD:"|":Y.PROPERTY:"|":Y.FIELD.CAMPO.RESTRUCT.TYPE:";;":Y.FIELD.ESTATUS:";;":Y.FIELD.FECHA.STATU:";;":Y.FIELD.COND:"|":"RN":";;":"Restructured":";;":TODAY:";;":"Restructured":"|"
    CALL F.WRITE(FN.LAPAP.CONCATE.RN.RT,Y.ARRANGEMENT.ID,R.LAPAP.CONCATE.RN.RT)


RETURN


CREAR.REGISTRO.INFINE.RT:

    Y.ACTIVIDAD = "LENDING-UPDATE-APAP.OVERDUE"
    Y.PROPERTY = "APAP.OVERDUE"
    Y.ARCHIVO.CARGA = "LOAD.CONDITION.txt"
    Y.FILE.LOAD.NAME = "AA.LIST.UPD"
    Y.COMPO.STATUS = "L.LOAN.STATUS.1"
    Y.CAMPO.FECHA.CAMBIO.STATUS = "L.STATUS.CHG.DT"
    Y.CAMPO.TIPO.RECTRUCTURADO = "L.RESTRUCT.TYPE"
    Y.CAMPO.COND = "L.LOAN.COND"
    Y.FILE.FINAL = "AA.LIST.UPD"
    Y.CONT.COND = DCOUNT(Y.CONDICION,@FM)
    Y.NUM.COND = Y.CONT.COND + 1;
    Y.FIELD.CAMPO.RESTRUCT.TYPE = "L.RESTRUCT.TYPE:1"
    Y.FIELD.FECHA.STATU = Y.CAMPO.FECHA.CAMBIO.STATUS:":":"1"
    Y.FIELD.COND = Y.CAMPO.COND:":":Y.NUM.COND
    R.LAPAP.CONCATE.RN.RT = Y.ARRANGEMENT.ID:"|":Y.ACTIVIDAD:"|":Y.PROPERTY:"|":Y.FIELD.CAMPO.RESTRUCT.TYPE:";;":Y.FIELD.FECHA.STATU:";;":Y.FIELD.COND:"|RT;;":TODAY:";;RT|"
    CALL F.WRITE (FN.LAPAP.CONCATE.RN.RT,Y.ARRANGEMENT.ID,R.LAPAP.CONCATE.RN.RT)


RETURN

END
