$PACKAGE EB.Repgen
  SUBROUTINE RGS.LIM.AL.POSITION
REM "RGS.LIM.AL.POSITION",230614-4
*************************************************************************
$INSERT I_COMMON
$INSERT I_EQUATE
$INSERT I_RC.COMMON
$INSERT I_SCREEN.VARIABLES
$INSERT I_F.COMPANY
$INSERT I_F.USER
$INSERT I_F.STANDARD.SELECTION
$INSERT I_F.DATES
  SAVE.ID.COMPANY = ID.COMPANY
*************************************************************************
  RG.S.CONCAT.IDS = "RG.S.CONCAT.IDS"
  RG.S.CONVERT = "RG.S.CONVERT"
  RG.S.CUS.AL.POS = "RG.S.CUS.AL.POS"
  RG.S.LIMIT.LINE.IDS = "RG.S.LIMIT.LINE.IDS"
  RG.S.LIMIT.ID.TYPES = "RG.S.LIMIT.ID.TYPES"
  RG.S.XCURRENCY = "RG.S.XCURRENCY"
  RG.S.LIMIT.ACCOUNT.OS = "RG.S.LIMIT.ACCOUNT.OS"
  RG.S.MULTIPLY = "RG.S.MULTIPLY"
  RG.S.HIGHEST = "RG.S.HIGHEST"
  RG.S.REPLACE.SUM = "RG.S.REPLACE.SUM"
  RG.S.LIMIT.COLLAT.RIGHT = "RG.S.LIMIT.COLLAT.RIGHT"
  RG.S.LIMIT.SECURED.AMT = "RG.S.LIMIT.SECURED.AMT"
  RG.S.SUM = "RG.S.SUM"
*************************************************************************
  YT.SMS.COMP = ID.COMPANY
  YT.SMS.FILE = "CUSTOMER"
  YT.SMS.FILE<-1> = "REPGEN.SORT"
  YT.SMS.FILE<-1> = "DEPT.ACCT.OFFICER"
  YT.SMS.FILE<-1> = "LIMIT"
  YT.SMS.FILE<-1> = "LIMIT.REFERENCE"
  YT.SMS.FILE<-1> = "COLLATERAL.RIGHT"
  YT.SMS.FILE<-1> = "COLLATERAL.CODE"
  YCOUNT = COUNT(YT.SMS.FILE,@FM)+1
  LOOP
    YID.COMP = YT.SMS.COMP<1>; DEL YT.SMS.COMP<1>
    FOR YAF = 1 TO YCOUNT
      YSMS.FILE = YT.SMS.FILE<YAF>
      YPW.OK = 0; Y = 1; X = 1
      LOOP WHILE X DO
        LOCATE YSMS.FILE IN R.USER<EB.USE.APPLICATION,Y> SETTING X ELSE X = 0
        IF X THEN
          GOSUB 9300000
          IF X THEN
            IF R.USER<EB.USE.FUNCTION,X> = "N" THEN
              IF R.USER<EB.USE.VERSION,X> THEN
                Y += 1; X = 1
              END ELSE
                X = 0; YPW.OK = "NO"
              END
            END ELSE
              Y = X+1; YPW.OK = 1; X = 0
            END
          END ELSE
            Y += 1; X = 1
          END
        END
* update pointers to definitions in version record
      REPEAT
      IF NOT(YPW.OK) THEN
* when no password for selected pgm ask for a global password
        LOCATE "ALL.PG" IN R.USER<EB.USE.APPLICATION,1> SETTING X ELSE X = 0
        GOSUB 9300000
* ask for a password for all programs
        IF NOT(X) THEN
          YPGM.TYPE = ""; CALL PGM.TABLE (YSMS.FILE, YPGM.TYPE)  
          Y = "ALL.PG.":YPGM.TYPE[1,1]
          LOCATE Y IN R.USER<EB.USE.APPLICATION,1> SETTING X ELSE X = 0
          GOSUB 9300000
* ask for a password for the type of the program
        END
        YPW.OK = 1
      END
      IF NOT(YPW.OK) OR YPW.OK = "NO" THEN
      MSG = "NO PASSWORD FOR FILE=":YSMS.FILE 
      MSG<2> = "SECURITY" 
        CALL PRO("NO PASSWORD FOR FILE=":YSMS.FILE)  
        TEXT = "SECURITY VIOLATION"
        CALL REM  ; RETURN  ;* end of pgm
      END
    NEXT YAF
  WHILE YT.SMS.COMP REPEAT
*************************************************************************
  YBLOCKNO = 0; YKEYNO = 0; YWRITNO = 0
  YT.FORFIL = ""; YKEYFD = ""
  YFD.LEN = ""; YPART.S = ""; YPART.L = ""
  DIM YR.REC(134)
  YFILE = "F":R.COMPANY(EB.COM.MNEMONIC):".RGS.LIM.AL.POSITION"
  YOLDFILE = 1
  OPEN "", YFILE TO F.FILE ELSE YOLDFILE = 0
  IF NOT(PHNO) THEN PRINT @(0,10):
  IF YOLDFILE THEN
     CLEARFILE F.FILE
     PRINT "FILE ":YFILE:"  CLEARED"
  END ELSE
    ERROR.MESSAGE = ""
    Y.OUT.FILE = FIELD(YFILE,".",2,99)
    SCHEMA.NAME = ""
    CALL EB.DETERMINE.SCHEMA(Y.OUT.FILE, ID.COMPANY, SCHEMA.NAME)
    IF SCHEMA.NAME THEN
        Y.OUT.FILE<7> = SCHEMA.NAME
    END
    CALL EBS.CREATE.FILE(Y.OUT.FILE,"",ERROR.MESSAGE)
  END
  OPEN "", YFILE TO F.FILE ELSE
    TEXT = "CANNOT OPEN ":YFILE
    CALL FATAL.ERROR ("RGS.LIM.AL.POSITION")
  END
*
  YCOM = ID.COMPANY
*
  YT.SMS = ""
  YT.SMS.FILE = "CUSTOMER"
  YT.SMS.FILE<-1> = "REPGEN.SORT"
  YT.SMS.FILE<-1> = "DEPT.ACCT.OFFICER"
  YT.SMS.FILE<-1> = "LIMIT"
  YT.SMS.FILE<-1> = "LIMIT.REFERENCE"
  YT.SMS.FILE<-1> = "COLLATERAL.RIGHT"
  YT.SMS.FILE<-1> = "COLLATERAL.CODE"
  YCOUNT = COUNT(R.USER<EB.USE.APPLICATION>,@VM)+1
  FOR YAV = 1 TO YCOUNT
    IF R.USER<EB.USE.DATA.COMPARISON,YAV> THEN
      YRESTR = R.USER<EB.USE.COMPANY.RESTR,YAV>
      IF YRESTR THEN
         IF YRESTR = YCOM THEN YRESTR = ""
      END
      IF NOT(YRESTR) THEN
        YAPPLI = R.USER<EB.USE.APPLICATION,YAV>
        LOCATE YAPPLI IN YT.SMS.FILE<1> SETTING X ELSE X = 0
        IF X THEN
          IF (INDEX(R.USER<EB.USE.FUNCTION,YAV>,"P",1)) OR (INDEX(R.USER<EB.USE.FUNCTION,YAV>,"S",1)) THEN
          LOCATE YAPPLI IN YT.SMS<1,1> SETTING X ELSE
            YT.SMS<1,-1> = YAPPLI
          END
          YT.SMS<2,X,-1> = YAV
          END
        END
      END
    END
  NEXT YAV
*
  YFILE = "F.REPGEN.SORT"; YF.REPGEN.SORT = ""
  CALL OPF (YFILE, YF.REPGEN.SORT)
  YFILE = "F.CUSTOMER"; YF.CUSTOMER = ""
  CALL OPF (YFILE, YF.CUSTOMER)
  YFILE = "F.DEPT.ACCT.OFFICER"; YF.DEPT.ACCT.OFFICER = ""
  CALL OPF (YFILE, YF.DEPT.ACCT.OFFICER)
  YFILE = "F.LIMIT"; YF.LIMIT = ""
  CALL OPF (YFILE, YF.LIMIT)
  YFILE = "F.LIMIT.REFERENCE"; YF.LIMIT.REFERENCE = ""
  CALL OPF (YFILE, YF.LIMIT.REFERENCE)
  YFILE = "F.COLLATERAL.RIGHT"; YF.COLLATERAL.RIGHT = ""
  CALL OPF (YFILE, YF.COLLATERAL.RIGHT)
  YFILE = "F.COLLATERAL.CODE"; YF.COLLATERAL.CODE = ""
  CALL OPF (YFILE, YF.COLLATERAL.CODE)
*************************************************************************
  YFILE = "CUSTOMER"
  FULL.FNAME = "F.CUSTOMER"; YF.CUSTOMER = ""
  LOCATE YFILE IN YT.SMS<1,1> SETTING X ELSE
    X = 0; T.PWD = ""
  END
  IF X THEN
    T.PWD = YT.SMS<2,X>
    CONVERT @SM TO @FM IN T.PWD
  END
 SS.REC = ""
 CALL GET.STANDARD.SELECTION.DETS(YFILE,SS.REC)
 LOCATE "CO.CODE" IN SS.REC<SSL.SYS.FIELD.NAME,1> SETTING COMP.FOUND ELSE COMP.FOUND = ""
  CALL OPF (FULL.FNAME, YF.CUSTOMER)
  CLEARSELECT
 IF C$MULTI.BOOK AND COMP.FOUND THEN
     SEL.ARGS = " WITH CO.CODE EQUAL ":ID.COMPANY
 END ELSE 
     SEL.ARGS = ""
 END
  SELECT.CMMD = "SELECT ":FULL.FNAME:SEL.ARGS
  CALL EB.READLIST(SELECT.CMMD,YID.LIST,"","","")
  LOOP
    REMOVE ID.NEW FROM YID.LIST SETTING YDELIM
  WHILE ID.NEW:YDELIM
    MATREAD R.NEW FROM YF.CUSTOMER, ID.NEW ELSE ID.NEW = "" ; MAT R.NEW = ""
    IF T.PWD THEN
      CALL CONTROL.USER.PROFILE ("RECORD")
      IF ETEXT THEN ID.NEW = ""
    END
    IF ID.NEW <> "" THEN
*
* Handle Decision Table
      YM.CUSTOMER.ID = ID.NEW
      YM.LIABILITY.NO = YM.CUSTOMER.ID
      IF YM.LIABILITY.NO <> "" THEN
        YCOMP = "CUSTOMER_25_":YM.LIABILITY.NO
        YFORFIL = YF.CUSTOMER
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.LIABILITY.NO = YFOR.FD
      END
      YM.CUSTOMER.NO = YM.CUSTOMER.ID
      YM.SORT.LIABILITY = "LIM.AL.POSITION"
      IF YM.SORT.LIABILITY <> "" THEN
        YCOMP = "REPGEN.SORT_5.4.1_":YM.SORT.LIABILITY
        YFORFIL = YF.REPGEN.SORT
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.SORT.LIABILITY = YFOR.FD
      END
      YM.SORT.ACCT.OFFICER = "LIM.AL.POSITION"
      IF YM.SORT.ACCT.OFFICER <> "" THEN
        YCOMP = "REPGEN.SORT_5.1.1_":YM.SORT.ACCT.OFFICER
        YFORFIL = YF.REPGEN.SORT
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.SORT.ACCT.OFFICER = YFOR.FD
      END
      YM.DEPT.ACCT.OFFICER = YM.CUSTOMER.ID
      IF YM.DEPT.ACCT.OFFICER <> "" THEN
        YCOMP = "CUSTOMER_11_":YM.DEPT.ACCT.OFFICER
        YFORFIL = YF.CUSTOMER
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.DEPT.ACCT.OFFICER = YFOR.FD
      END
      YM.SORT.CUSTOMER = "LIM.AL.POSITION"
      IF YM.SORT.CUSTOMER <> "" THEN
        YCOMP = "REPGEN.SORT_5.2.1_":YM.SORT.CUSTOMER
        YFORFIL = YF.REPGEN.SORT
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.SORT.CUSTOMER = YFOR.FD
      END
      YM.CUSTOMER.PRINT = YM.CUSTOMER.ID
      IF YM.CUSTOMER.PRINT <> "" THEN
        YCOMP = "CUSTOMER_39_":YM.CUSTOMER.PRINT
        YFORFIL = YF.CUSTOMER
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.CUSTOMER.PRINT = YFOR.FD
      END
      IF (YM.LIABILITY.NO = "" OR YM.LIABILITY.NO = YM.CUSTOMER.NO OR YM.SORT.LIABILITY <> "") AND (YM.SORT.ACCT.OFFICER = "" OR YM.DEPT.ACCT.OFFICER = YM.SORT.ACCT.OFFICER) AND ((YM.SORT.CUSTOMER = "" AND YM.CUSTOMER.PRINT <> "NO") OR YM.CUSTOMER.NO = YM.SORT.CUSTOMER) THEN
        GOSUB 2000000
      END
1000:
    END
*
  REPEAT
  IF YKEYNO THEN
  YR.REC(134)  := @FM
     MATWRITE YR.REC TO F.FILE, YKEY
  END 
*
  IF NOT(PHNO) THEN PRINT @(41,L1ST-3):YBLOCKNO+YWRITNO:
  IF SAVE.ID.COMPANY # ID.COMPANY THEN
     CALL LOAD.COMPANY(SAVE.ID.COMPANY)
  END
  RETURN
*************************************************************************
*
* Define and Write record
2000000:
*
  YKEY = ""; MAT YR.REC = ""
  YM.CUSTOMER.ID = ID.NEW
  YM.DEPT.ACCT.OFFICER = YM.CUSTOMER.ID
  IF YM.DEPT.ACCT.OFFICER <> "" THEN
    YCOMP = "CUSTOMER_11_":YM.DEPT.ACCT.OFFICER
    YFORFIL = YF.CUSTOMER
    YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
    YM.DEPT.ACCT.OFFICER = YFOR.FD
  END
  YKEYFD = FMT(YM.DEPT.ACCT.OFFICER,"R####")
  IF LEN(YKEYFD) > 4 THEN YKEYFD = YKEYFD[1,3]:"|"
  GOSUB 8000000
  YR.REC(1) = YM.DEPT.ACCT.OFFICER
  YM.NAME = YM.DEPT.ACCT.OFFICER
  IF YM.NAME <> "" THEN
    YCOMP = "DEPT.ACCT.OFFICER_2_":YM.NAME
    YFORFIL = YF.DEPT.ACCT.OFFICER
    YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
    YM.NAME = YFOR.FD
  END
  YR.REC(2) = YM.NAME
  YM.CUSTOMER.NO = YM.CUSTOMER.ID
  YKEYFD = FMT(YM.CUSTOMER.NO,"R######")
  IF LEN(YKEYFD) > 6 THEN YKEYFD = YKEYFD[1,5]:"|"
  GOSUB 8000000
  YR.REC(3) = YM.CUSTOMER.NO
  YM.NAME.1 = YM.CUSTOMER.NO
  IF YM.NAME.1 <> "" THEN
    YCOMP = "CUSTOMER_3_":YM.NAME.1
    YFORFIL = YF.CUSTOMER
    YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
    YM.NAME.1 = YFOR.FD
  END
  YR.REC(4) = YM.NAME.1
  YM.SORT.CURRENCY = "LIM.AL.POSITION"
  IF YM.SORT.CURRENCY <> "" THEN
    YCOMP = "REPGEN.SORT_5.3.1_":YM.SORT.CURRENCY
    YFORFIL = YF.REPGEN.SORT
    YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
    YM.SORT.CURRENCY = YFOR.FD
  END
  YM.CURRENCY1 = YM.SORT.CURRENCY
  YM1.CURRENCY1 = YM.CURRENCY1
  YM.CUSTOMER.CURRENCY = YM.CUSTOMER.NO
  IF YM.CUSTOMER.CURRENCY <> "" THEN
    YCOMP = "CUSTOMER_38_":YM.CUSTOMER.CURRENCY
    YFORFIL = YF.CUSTOMER
    YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
    YM.CUSTOMER.CURRENCY = YFOR.FD
  END
  YM.CURRENCY1 = YM.CUSTOMER.CURRENCY
  YM1.CURRENCY1 = YM1.CURRENCY1 : YM.CURRENCY1
  YM.CURRENCY1 = YM1.CURRENCY1
  YM.CURRENCY2 = YM.CURRENCY1
  YM1.CURRENCY2 = YM.CURRENCY2
  YM.CURRENCY2 = "USD"
  YM1.CURRENCY2 = YM1.CURRENCY2 : YM.CURRENCY2
  YM.CURRENCY2 = YM1.CURRENCY2
  YM.CURRENCY = YM.CURRENCY2
  YM.CURRENCY = FMT(YM.CURRENCY,"3L"); YM.CURRENCY = YM.CURRENCY[1,3]
  YR.REC(5) = YM.CURRENCY
  YTRUE.1 = 0
  YM.LIABILITY.NO = YM.CUSTOMER.ID
  IF YM.LIABILITY.NO <> "" THEN
    YCOMP = "CUSTOMER_25_":YM.LIABILITY.NO
    YFORFIL = YF.CUSTOMER
    YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
    YM.LIABILITY.NO = YFOR.FD
  END
  YM.ARG.A1 = YM.LIABILITY.NO
  YM16.GOSUB = YM.ARG.A1
  YM.ARG.A2 = "CUSTOMER.LIABILITY"
  YM17.GOSUB = YM.ARG.A2
  YM.ARG.A3 = ""
  YM18.GOSUB = YM.ARG.A3
  CALL @RG.S.CONCAT.IDS (YM16.GOSUB, YM17.GOSUB, YM18.GOSUB)
  YM.ARG.A1 = YM16.GOSUB
  YM.ARG.A2 = YM17.GOSUB
  YM.ARG.A3 = YM18.GOSUB
  YM.SORT.LIABILITY = "LIM.AL.POSITION"
  IF YM.SORT.LIABILITY <> "" THEN
    YCOMP = "REPGEN.SORT_5.4.1_":YM.SORT.LIABILITY
    YFORFIL = YF.REPGEN.SORT
    YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
    YM.SORT.LIABILITY = YFOR.FD
  END
  IF YM.ARG.A3 <> "" AND YM.SORT.LIABILITY = "" THEN
    YTRUE.1 = 1
    YM.ARG.B1 = "@VM"
    YM19.GOSUB = YM.ARG.B1
    YM.ARG.B2 = " "
    YM20.GOSUB = YM.ARG.B2
    YM.ARG.B3 = YM.ARG.A3
    YM21.GOSUB = YM.ARG.B3
    CALL @RG.S.CONVERT (YM19.GOSUB, YM20.GOSUB, YM21.GOSUB)
    YM.ARG.B1 = YM19.GOSUB
    YM.ARG.B2 = YM20.GOSUB
    YM.ARG.B3 = YM21.GOSUB
    YM.LIABILITY.GROUP = YM.ARG.B3
  END
  IF NOT(YTRUE.1) THEN YM.LIABILITY.GROUP = ""
  YR.REC(6) = YM.LIABILITY.GROUP
  YM.TEXT.1 = ""
  YR.REC(7) = YM.TEXT.1
  YM.TEXT.2 = "L I A B I L I T Y"
  YR.REC(8) = YM.TEXT.2
  YM.TEXT.3 = "A S S E T"
  YR.REC(9) = YM.TEXT.3
  YM.TEXT.4 = "LINE"
  YR.REC(10) = YM.TEXT.4
  YM.TEXT.5 = "MARKET"
  YR.REC(11) = YM.TEXT.5
  YM.TEXT.6 = "LINE"
  YR.REC(12) = YM.TEXT.6
  YM.TEXT.7 = "MARKET"
  YR.REC(13) = YM.TEXT.7
  YM.TEXT.8 = "MARGIN"
  YR.REC(14) = YM.TEXT.8
  YM.TEXT.9 = "MARGIN"
  YR.REC(15) = YM.TEXT.9
  YM.TEXT.11 = "VALUE"
  YR.REC(16) = YM.TEXT.11
  YM.TEXT.12 = "VALUE"
  YR.REC(17) = YM.TEXT.12
  YM.TEXT.13 = "VALUE"
  YR.REC(18) = YM.TEXT.13
  YM.TEXT.14 = "VALUE"
  YR.REC(19) = YM.TEXT.14
  YM.TEXT.16 = "Unpledged"
  YR.REC(20) = YM.TEXT.16
  YM.TEXT.17 = "Pledged"
  YR.REC(21) = YM.TEXT.17
  YM.TEXT.18 = ""
  YR.REC(22) = YM.TEXT.18
  YM.TEXT.19 = "CASH LIABILITIES"
  YR.REC(23) = YM.TEXT.19
  YM.TEXT.20 = "CASH ASSETS"
  YR.REC(24) = YM.TEXT.20
  YTRUE.1 = 0
  YM.SORT.LIABILITY = "LIM.AL.POSITION"
  IF YM.SORT.LIABILITY <> "" THEN
    YCOMP = "REPGEN.SORT_5.4.1_":YM.SORT.LIABILITY
    YFORFIL = YF.REPGEN.SORT
    YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
    YM.SORT.LIABILITY = YFOR.FD
  END
  IF YM.ARG.A3 = "" OR YM.SORT.LIABILITY <> "" THEN
    YTRUE.1 = 1
    YM.SINGLE.CUSTOMER = YM.CUSTOMER.NO
  END
  IF NOT(YTRUE.1) THEN YM.SINGLE.CUSTOMER = ""
  YM.CUSTOMER.GROUP = YM.SINGLE.CUSTOMER
  YM1.CUSTOMER.GROUP = YM.CUSTOMER.GROUP
  YTRUE.1 = 0
  YM.SORT.LIABILITY = "LIM.AL.POSITION"
  IF YM.SORT.LIABILITY <> "" THEN
    YCOMP = "REPGEN.SORT_5.4.1_":YM.SORT.LIABILITY
    YFORFIL = YF.REPGEN.SORT
    YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
    YM.SORT.LIABILITY = YFOR.FD
  END
  IF YM.ARG.A3 <> "" AND YM.SORT.LIABILITY = "" THEN
    YTRUE.1 = 1
    YM.MULTI.CUSTOMER = YM.ARG.A3
  END
  IF NOT(YTRUE.1) THEN YM.MULTI.CUSTOMER = ""
  YM.CUSTOMER.GROUP = YM.MULTI.CUSTOMER
  YM1.CUSTOMER.GROUP = YM1.CUSTOMER.GROUP : YM.CUSTOMER.GROUP
  YM.CUSTOMER.GROUP = YM1.CUSTOMER.GROUP
  YM.ARG.C1 = YM.CUSTOMER.GROUP
  YM44.GOSUB = YM.ARG.C1
  YM.ARG.C2 = "L"
  YM45.GOSUB = YM.ARG.C2
  YM.ARG.C3 = "AC"
  YM46.GOSUB = YM.ARG.C3
  YM.ARG.C4 = ""
  YM47.GOSUB = YM.ARG.C4
  YM.ARG.C5 = YM.CURRENCY
  YM48.GOSUB = YM.ARG.C5
  YM.ARG.C6 = ""
  YM49.GOSUB = YM.ARG.C6
  YM.ARG.C7 = ""
  YM50.GOSUB = YM.ARG.C7
  YM.ARG.C8 = ""
  YM51.GOSUB = YM.ARG.C8
  CALL @RG.S.CUS.AL.POS (YM44.GOSUB, YM45.GOSUB, YM46.GOSUB, YM47.GOSUB, YM48.GOSUB, YM49.GOSUB, YM50.GOSUB, YM51.GOSUB)
  YM.ARG.C1 = YM44.GOSUB
  YM.ARG.C2 = YM45.GOSUB
  YM.ARG.C3 = YM46.GOSUB
  YM.ARG.C4 = YM47.GOSUB
  YM.ARG.C5 = YM48.GOSUB
  YM.ARG.C6 = YM49.GOSUB
  YM.ARG.C7 = YM50.GOSUB
  YM.ARG.C8 = YM51.GOSUB
  YM.OVERDRAFT = YM.ARG.C6
  YR.REC(25) = YM.OVERDRAFT
  YM.ARG.D1 = YM.CUSTOMER.GROUP
  YM53.GOSUB = YM.ARG.D1
  YM.ARG.D2 = "A"
  YM54.GOSUB = YM.ARG.D2
  YM.ARG.D3 = "AC"
  YM55.GOSUB = YM.ARG.D3
  YM.ARG.D4 = "CASH"
  YM56.GOSUB = YM.ARG.D4
  YM.ARG.D5 = YM.CURRENCY
  YM57.GOSUB = YM.ARG.D5
  YM.ARG.D6 = ""
  YM58.GOSUB = YM.ARG.D6
  YM.ARG.D7 = ""
  YM59.GOSUB = YM.ARG.D7
  YM.ARG.D8 = ""
  YM60.GOSUB = YM.ARG.D8
  CALL @RG.S.CUS.AL.POS (YM53.GOSUB, YM54.GOSUB, YM55.GOSUB, YM56.GOSUB, YM57.GOSUB, YM58.GOSUB, YM59.GOSUB, YM60.GOSUB)
  YM.ARG.D1 = YM53.GOSUB
  YM.ARG.D2 = YM54.GOSUB
  YM.ARG.D3 = YM55.GOSUB
  YM.ARG.D4 = YM56.GOSUB
  YM.ARG.D5 = YM57.GOSUB
  YM.ARG.D6 = YM58.GOSUB
  YM.ARG.D7 = YM59.GOSUB
  YM.ARG.D8 = YM60.GOSUB
  YM.CASH.BALANCE = YM.ARG.D6
  YR.REC(26) = YM.CASH.BALANCE
  YM.CASH.UNPLEDGED = YM.ARG.D7
  YR.REC(27) = YM.CASH.UNPLEDGED
  YM.CASH.PLEDGED = YM.ARG.D8
  YR.REC(28) = YM.CASH.PLEDGED
  YM.ARG.D1A = YM.CUSTOMER.GROUP
  YM64.GOSUB = YM.ARG.D1A
  YM.ARG.D2A = "L"
  YM65.GOSUB = YM.ARG.D2A
  YM.ARG.D3A = "AC"
  YM66.GOSUB = YM.ARG.D3A
  YM.ARG.D4A = "METAL"
  YM67.GOSUB = YM.ARG.D4A
  YM.ARG.D5A = YM.CURRENCY
  YM68.GOSUB = YM.ARG.D5A
  YM.ARG.D6A = ""
  YM69.GOSUB = YM.ARG.D6A
  YM.ARG.D7A = ""
  YM70.GOSUB = YM.ARG.D7A
  YM.ARG.D8A = ""
  YM71.GOSUB = YM.ARG.D8A
  CALL @RG.S.CUS.AL.POS (YM64.GOSUB, YM65.GOSUB, YM66.GOSUB, YM67.GOSUB, YM68.GOSUB, YM69.GOSUB, YM70.GOSUB, YM71.GOSUB)
  YM.ARG.D1A = YM64.GOSUB
  YM.ARG.D2A = YM65.GOSUB
  YM.ARG.D3A = YM66.GOSUB
  YM.ARG.D4A = YM67.GOSUB
  YM.ARG.D5A = YM68.GOSUB
  YM.ARG.D6A = YM69.GOSUB
  YM.ARG.D7A = YM70.GOSUB
  YM.ARG.D8A = YM71.GOSUB
  YM.SHORT.METAL = YM.ARG.D6A
  YR.REC(29) = YM.SHORT.METAL
  YM.ARG.E1 = YM.CUSTOMER.GROUP
  YM73.GOSUB = YM.ARG.E1
  YM.ARG.E2 = "A"
  YM74.GOSUB = YM.ARG.E2
  YM.ARG.E3 = "AC"
  YM75.GOSUB = YM.ARG.E3
  YM.ARG.E4 = "METAL"
  YM76.GOSUB = YM.ARG.E4
  YM.ARG.E5 = YM.CURRENCY
  YM77.GOSUB = YM.ARG.E5
  YM.ARG.E6 = ""
  YM78.GOSUB = YM.ARG.E6
  YM.ARG.E7 = ""
  YM79.GOSUB = YM.ARG.E7
  YM.ARG.E8 = ""
  YM80.GOSUB = YM.ARG.E8
  CALL @RG.S.CUS.AL.POS (YM73.GOSUB, YM74.GOSUB, YM75.GOSUB, YM76.GOSUB, YM77.GOSUB, YM78.GOSUB, YM79.GOSUB, YM80.GOSUB)
  YM.ARG.E1 = YM73.GOSUB
  YM.ARG.E2 = YM74.GOSUB
  YM.ARG.E3 = YM75.GOSUB
  YM.ARG.E4 = YM76.GOSUB
  YM.ARG.E5 = YM77.GOSUB
  YM.ARG.E6 = YM78.GOSUB
  YM.ARG.E7 = YM79.GOSUB
  YM.ARG.E8 = YM80.GOSUB
  YM.METAL.BALANCE = YM.ARG.E6
  YR.REC(30) = YM.METAL.BALANCE
  YM.METAL.UNPLEDGED = YM.ARG.E7
  YR.REC(31) = YM.METAL.UNPLEDGED
  YM.METAL.PLEDGED = YM.ARG.E8
  YR.REC(32) = YM.METAL.PLEDGED
  YM.ARG.F1 = YM.CUSTOMER.GROUP
  YM84.GOSUB = YM.ARG.F1
  YM.ARG.F2 = "L"
  YM85.GOSUB = YM.ARG.F2
  YM.ARG.F3 = "LD"
  YM86.GOSUB = YM.ARG.F3
  YM.ARG.F4 = ""
  YM87.GOSUB = YM.ARG.F4
  YM.ARG.F5 = YM.CURRENCY
  YM88.GOSUB = YM.ARG.F5
  YM.ARG.F6 = ""
  YM89.GOSUB = YM.ARG.F6
  YM.ARG.F7 = ""
  YM90.GOSUB = YM.ARG.F7
  YM.ARG.F8 = ""
  YM91.GOSUB = YM.ARG.F8
  CALL @RG.S.CUS.AL.POS (YM84.GOSUB, YM85.GOSUB, YM86.GOSUB, YM87.GOSUB, YM88.GOSUB, YM89.GOSUB, YM90.GOSUB, YM91.GOSUB)
  YM.ARG.F1 = YM84.GOSUB
  YM.ARG.F2 = YM85.GOSUB
  YM.ARG.F3 = YM86.GOSUB
  YM.ARG.F4 = YM87.GOSUB
  YM.ARG.F5 = YM88.GOSUB
  YM.ARG.F6 = YM89.GOSUB
  YM.ARG.F7 = YM90.GOSUB
  YM.ARG.F8 = YM91.GOSUB
  YM.LOAN.BALANCE = YM.ARG.F6
  YM1.LOAN.BALANCE = YM.LOAN.BALANCE
  YM.ARG.H1 = YM.CUSTOMER.GROUP
  YM100.GOSUB = YM.ARG.H1
  YM.ARG.H2 = "L"
  YM101.GOSUB = YM.ARG.H2
  YM.ARG.H3 = "MM"
  YM102.GOSUB = YM.ARG.H3
  YM.ARG.H4 = ""
  YM103.GOSUB = YM.ARG.H4
  YM.ARG.H5 = YM.CURRENCY
  YM104.GOSUB = YM.ARG.H5
  YM.ARG.H6 = ""
  YM105.GOSUB = YM.ARG.H6
  YM.ARG.H7 = ""
  YM106.GOSUB = YM.ARG.H7
  YM.ARG.H8 = ""
  YM107.GOSUB = YM.ARG.H8
  CALL @RG.S.CUS.AL.POS (YM100.GOSUB, YM101.GOSUB, YM102.GOSUB, YM103.GOSUB, YM104.GOSUB, YM105.GOSUB, YM106.GOSUB, YM107.GOSUB)
  YM.ARG.H1 = YM100.GOSUB
  YM.ARG.H2 = YM101.GOSUB
  YM.ARG.H3 = YM102.GOSUB
  YM.ARG.H4 = YM103.GOSUB
  YM.ARG.H5 = YM104.GOSUB
  YM.ARG.H6 = YM105.GOSUB
  YM.ARG.H7 = YM106.GOSUB
  YM.ARG.H8 = YM107.GOSUB
  YM.LOAN.BALANCE = YM.ARG.H6
  IF NUM(YM1.LOAN.BALANCE) = NUMERIC THEN IF NUM(YM.LOAN.BALANCE) = NUMERIC THEN
    YM1.LOAN.BALANCE = YM1.LOAN.BALANCE + YM.LOAN.BALANCE
    IF YM1.LOAN.BALANCE = 0 THEN YM1.LOAN.BALANCE = ""
  END
  YM.LOAN.BALANCE = YM1.LOAN.BALANCE
  YR.REC(33) = YM.LOAN.BALANCE
  YM.ARG.G1 = YM.CUSTOMER.GROUP
  YM92.GOSUB = YM.ARG.G1
  YM.ARG.G2 = "A"
  YM93.GOSUB = YM.ARG.G2
  YM.ARG.G3 = "LD"
  YM94.GOSUB = YM.ARG.G3
  YM.ARG.G4 = ""
  YM95.GOSUB = YM.ARG.G4
  YM.ARG.G5 = YM.CURRENCY
  YM96.GOSUB = YM.ARG.G5
  YM.ARG.G6 = ""
  YM97.GOSUB = YM.ARG.G6
  YM.ARG.G7 = ""
  YM98.GOSUB = YM.ARG.G7
  YM.ARG.G8 = ""
  YM99.GOSUB = YM.ARG.G8
  CALL @RG.S.CUS.AL.POS (YM92.GOSUB, YM93.GOSUB, YM94.GOSUB, YM95.GOSUB, YM96.GOSUB, YM97.GOSUB, YM98.GOSUB, YM99.GOSUB)
  YM.ARG.G1 = YM92.GOSUB
  YM.ARG.G2 = YM93.GOSUB
  YM.ARG.G3 = YM94.GOSUB
  YM.ARG.G4 = YM95.GOSUB
  YM.ARG.G5 = YM96.GOSUB
  YM.ARG.G6 = YM97.GOSUB
  YM.ARG.G7 = YM98.GOSUB
  YM.ARG.G8 = YM99.GOSUB
  YM.DEPOSIT.BALANCE = YM.ARG.G6
  YM1.DEPOSIT.BALANCE = YM.DEPOSIT.BALANCE
  YM.ARG.I1 = YM.CUSTOMER.GROUP
  YM108.GOSUB = YM.ARG.I1
  YM.ARG.I2 = "A"
  YM109.GOSUB = YM.ARG.I2
  YM.ARG.I3 = "MM"
  YM110.GOSUB = YM.ARG.I3
  YM.ARG.I4 = ""
  YM111.GOSUB = YM.ARG.I4
  YM.ARG.I5 = YM.CURRENCY
  YM112.GOSUB = YM.ARG.I5
  YM.ARG.I6 = ""
  YM113.GOSUB = YM.ARG.I6
  YM.ARG.I7 = ""
  YM114.GOSUB = YM.ARG.I7
  YM.ARG.I8 = ""
  YM115.GOSUB = YM.ARG.I8
  CALL @RG.S.CUS.AL.POS (YM108.GOSUB, YM109.GOSUB, YM110.GOSUB, YM111.GOSUB, YM112.GOSUB, YM113.GOSUB, YM114.GOSUB, YM115.GOSUB)
  YM.ARG.I1 = YM108.GOSUB
  YM.ARG.I2 = YM109.GOSUB
  YM.ARG.I3 = YM110.GOSUB
  YM.ARG.I4 = YM111.GOSUB
  YM.ARG.I5 = YM112.GOSUB
  YM.ARG.I6 = YM113.GOSUB
  YM.ARG.I7 = YM114.GOSUB
  YM.ARG.I8 = YM115.GOSUB
  YM.DEPOSIT.BALANCE = YM.ARG.I6
  IF NUM(YM1.DEPOSIT.BALANCE) = NUMERIC THEN IF NUM(YM.DEPOSIT.BALANCE) = NUMERIC THEN
    YM1.DEPOSIT.BALANCE = YM1.DEPOSIT.BALANCE + YM.DEPOSIT.BALANCE
    IF YM1.DEPOSIT.BALANCE = 0 THEN YM1.DEPOSIT.BALANCE = ""
  END
  YM.DEPOSIT.BALANCE = YM1.DEPOSIT.BALANCE
  YR.REC(34) = YM.DEPOSIT.BALANCE
  YM.DEPOSIT.UNPLEDGED = YM.ARG.G7
  YM1.DEPOSIT.UNPLEDGED = YM.DEPOSIT.UNPLEDGED
  YM.DEPOSIT.UNPLEDGED = YM.ARG.I7
  IF NUM(YM1.DEPOSIT.UNPLEDGED) = NUMERIC THEN IF NUM(YM.DEPOSIT.UNPLEDGED) = NUMERIC THEN
    YM1.DEPOSIT.UNPLEDGED = YM1.DEPOSIT.UNPLEDGED + YM.DEPOSIT.UNPLEDGED
    IF YM1.DEPOSIT.UNPLEDGED = 0 THEN YM1.DEPOSIT.UNPLEDGED = ""
  END
  YM.DEPOSIT.UNPLEDGED = YM1.DEPOSIT.UNPLEDGED
  YR.REC(35) = YM.DEPOSIT.UNPLEDGED
  YM.DEPOSIT.PLEDGED = YM.ARG.G8
  YM1.DEPOSIT.PLEDGED = YM.DEPOSIT.PLEDGED
  YM.DEPOSIT.PLEDGED = YM.ARG.I8
  IF NUM(YM1.DEPOSIT.PLEDGED) = NUMERIC THEN IF NUM(YM.DEPOSIT.PLEDGED) = NUMERIC THEN
    YM1.DEPOSIT.PLEDGED = YM1.DEPOSIT.PLEDGED + YM.DEPOSIT.PLEDGED
    IF YM1.DEPOSIT.PLEDGED = 0 THEN YM1.DEPOSIT.PLEDGED = ""
  END
  YM.DEPOSIT.PLEDGED = YM1.DEPOSIT.PLEDGED
  YR.REC(36) = YM.DEPOSIT.PLEDGED
  YM.ARG.J1 = YM.CUSTOMER.GROUP
  YM120.GOSUB = YM.ARG.J1
  YM.ARG.J2 = ""
  YM121.GOSUB = YM.ARG.J2
  YM.ARG.J3 = "FD"
  YM122.GOSUB = YM.ARG.J3
  YM.ARG.J4 = ""
  YM123.GOSUB = YM.ARG.J4
  YM.ARG.J5 = YM.CURRENCY
  YM124.GOSUB = YM.ARG.J5
  YM.ARG.J6 = ""
  YM125.GOSUB = YM.ARG.J6
  YM.ARG.J7 = ""
  YM126.GOSUB = YM.ARG.J7
  YM.ARG.J8 = ""
  YM127.GOSUB = YM.ARG.J8
  CALL @RG.S.CUS.AL.POS (YM120.GOSUB, YM121.GOSUB, YM122.GOSUB, YM123.GOSUB, YM124.GOSUB, YM125.GOSUB, YM126.GOSUB, YM127.GOSUB)
  YM.ARG.J1 = YM120.GOSUB
  YM.ARG.J2 = YM121.GOSUB
  YM.ARG.J3 = YM122.GOSUB
  YM.ARG.J4 = YM123.GOSUB
  YM.ARG.J5 = YM124.GOSUB
  YM.ARG.J6 = YM125.GOSUB
  YM.ARG.J7 = YM126.GOSUB
  YM.ARG.J8 = YM127.GOSUB
  YM.FIDUCIARY.BALANCE = YM.ARG.J6
  YR.REC(37) = YM.FIDUCIARY.BALANCE
  YM.FIDUCIARY.UNPLEDGED = YM.ARG.J7
  YR.REC(38) = YM.FIDUCIARY.UNPLEDGED
  YM.FIDUCIARY.PLEDGED = YM.ARG.J8
  YR.REC(39) = YM.FIDUCIARY.PLEDGED
  YM.ARG.J1A = YM.CUSTOMER.GROUP
  YM131.GOSUB = YM.ARG.J1A
  YM.ARG.J2A = "L"
  YM132.GOSUB = YM.ARG.J2A
  YM.ARG.J3A = "LD"
  YM133.GOSUB = YM.ARG.J3A
  YM.ARG.J4A = ""
  YM134.GOSUB = YM.ARG.J4A
  YM.ARG.J5A = YM.CURRENCY
  YM135.GOSUB = YM.ARG.J5A
  YM.ARG.J6A = ""
  YM136.GOSUB = YM.ARG.J6A
  YM.ARG.J7A = ""
  YM137.GOSUB = YM.ARG.J7A
  YM.ARG.J8A = ""
  YM138.GOSUB = YM.ARG.J8A
  CALL @RG.S.CUS.AL.POS (YM131.GOSUB, YM132.GOSUB, YM133.GOSUB, YM134.GOSUB, YM135.GOSUB, YM136.GOSUB, YM137.GOSUB, YM138.GOSUB)
  YM.ARG.J1A = YM131.GOSUB
  YM.ARG.J2A = YM132.GOSUB
  YM.ARG.J3A = YM133.GOSUB
  YM.ARG.J4A = YM134.GOSUB
  YM.ARG.J5A = YM135.GOSUB
  YM.ARG.J6A = YM136.GOSUB
  YM.ARG.J7A = YM137.GOSUB
  YM.ARG.J8A = YM138.GOSUB
  YM.DEBT.DIFF.PAYM = YM.ARG.J6A
  YR.REC(40) = YM.DEBT.DIFF.PAYM
  YM.ARG.J1B = YM.CUSTOMER.GROUP
  YM140.GOSUB = YM.ARG.J1B
  YM.ARG.J2B = "A"
  YM141.GOSUB = YM.ARG.J2B
  YM.ARG.J3B = "LD"
  YM142.GOSUB = YM.ARG.J3B
  YM.ARG.J4B = ""
  YM143.GOSUB = YM.ARG.J4B
  YM.ARG.J5B = YM.CURRENCY
  YM144.GOSUB = YM.ARG.J5B
  YM.ARG.J6B = ""
  YM145.GOSUB = YM.ARG.J6B
  YM.ARG.J7B = ""
  YM146.GOSUB = YM.ARG.J7B
  YM.ARG.J8B = ""
  YM147.GOSUB = YM.ARG.J8B
  CALL @RG.S.CUS.AL.POS (YM140.GOSUB, YM141.GOSUB, YM142.GOSUB, YM143.GOSUB, YM144.GOSUB, YM145.GOSUB, YM146.GOSUB, YM147.GOSUB)
  YM.ARG.J1B = YM140.GOSUB
  YM.ARG.J2B = YM141.GOSUB
  YM.ARG.J3B = YM142.GOSUB
  YM.ARG.J4B = YM143.GOSUB
  YM.ARG.J5B = YM144.GOSUB
  YM.ARG.J6B = YM145.GOSUB
  YM.ARG.J7B = YM146.GOSUB
  YM.ARG.J8B = YM147.GOSUB
  YM.CRED.DIFF.PAYM = YM.ARG.J6B
  YR.REC(41) = YM.CRED.DIFF.PAYM
  YM.CRED.DIFF.UNPLEDGED = YM.ARG.J7B
  YR.REC(42) = YM.CRED.DIFF.UNPLEDGED
  YM.CRED.DIFF.PLEDGED = YM.ARG.J8B
  YR.REC(43) = YM.CRED.DIFF.PLEDGED
  YM.TOTAL.CASH.DR.1 = YM.OVERDRAFT
  YM1.TOTAL.CASH.DR.1 = YM.TOTAL.CASH.DR.1
  YM.TOTAL.CASH.DR.1 = YM.LOAN.BALANCE
  IF NUM(YM1.TOTAL.CASH.DR.1) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.DR.1) = NUMERIC THEN
    YM1.TOTAL.CASH.DR.1 = YM1.TOTAL.CASH.DR.1 + YM.TOTAL.CASH.DR.1
    IF YM1.TOTAL.CASH.DR.1 = 0 THEN YM1.TOTAL.CASH.DR.1 = ""
  END
  YM.TOTAL.CASH.DR.1 = YM1.TOTAL.CASH.DR.1
  YM.TOTAL.CASH.DR = YM.TOTAL.CASH.DR.1
  YM1.TOTAL.CASH.DR = YM.TOTAL.CASH.DR
  YM.TOTAL.CASH.DR = YM.DEBT.DIFF.PAYM
  IF NUM(YM1.TOTAL.CASH.DR) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.DR) = NUMERIC THEN
    YM1.TOTAL.CASH.DR = YM1.TOTAL.CASH.DR + YM.TOTAL.CASH.DR
    IF YM1.TOTAL.CASH.DR = 0 THEN YM1.TOTAL.CASH.DR = ""
  END
  YM.TOTAL.CASH.DR = YM1.TOTAL.CASH.DR
  YR.REC(44) = YM.TOTAL.CASH.DR
  YM.TOTAL.CASH.CR.1 = YM.CASH.BALANCE
  YM1.TOTAL.CASH.CR.1 = YM.TOTAL.CASH.CR.1
  YM.TOTAL.CASH.CR.1 = YM.METAL.BALANCE
  IF NUM(YM1.TOTAL.CASH.CR.1) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.CR.1) = NUMERIC THEN
    YM1.TOTAL.CASH.CR.1 = YM1.TOTAL.CASH.CR.1 + YM.TOTAL.CASH.CR.1
    IF YM1.TOTAL.CASH.CR.1 = 0 THEN YM1.TOTAL.CASH.CR.1 = ""
  END
  YM.TOTAL.CASH.CR.1 = YM1.TOTAL.CASH.CR.1
  YM.TOTAL.CASH.CR.2 = YM.TOTAL.CASH.CR.1
  YM1.TOTAL.CASH.CR.2 = YM.TOTAL.CASH.CR.2
  YM.TOTAL.CASH.CR.2 = YM.DEPOSIT.BALANCE
  IF NUM(YM1.TOTAL.CASH.CR.2) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.CR.2) = NUMERIC THEN
    YM1.TOTAL.CASH.CR.2 = YM1.TOTAL.CASH.CR.2 + YM.TOTAL.CASH.CR.2
    IF YM1.TOTAL.CASH.CR.2 = 0 THEN YM1.TOTAL.CASH.CR.2 = ""
  END
  YM.TOTAL.CASH.CR.2 = YM1.TOTAL.CASH.CR.2
  YM.TOTAL.CASH.CR.3 = YM.TOTAL.CASH.CR.2
  YM1.TOTAL.CASH.CR.3 = YM.TOTAL.CASH.CR.3
  YM.TOTAL.CASH.CR.3 = YM.FIDUCIARY.BALANCE
  IF NUM(YM1.TOTAL.CASH.CR.3) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.CR.3) = NUMERIC THEN
    YM1.TOTAL.CASH.CR.3 = YM1.TOTAL.CASH.CR.3 + YM.TOTAL.CASH.CR.3
    IF YM1.TOTAL.CASH.CR.3 = 0 THEN YM1.TOTAL.CASH.CR.3 = ""
  END
  YM.TOTAL.CASH.CR.3 = YM1.TOTAL.CASH.CR.3
  YM.TOTAL.CASH.CR = YM.TOTAL.CASH.CR.3
  YM1.TOTAL.CASH.CR = YM.TOTAL.CASH.CR
  YM.TOTAL.CASH.CR = YM.CRED.DIFF.PAYM
  IF NUM(YM1.TOTAL.CASH.CR) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.CR) = NUMERIC THEN
    YM1.TOTAL.CASH.CR = YM1.TOTAL.CASH.CR + YM.TOTAL.CASH.CR
    IF YM1.TOTAL.CASH.CR = 0 THEN YM1.TOTAL.CASH.CR = ""
  END
  YM.TOTAL.CASH.CR = YM1.TOTAL.CASH.CR
  YR.REC(45) = YM.TOTAL.CASH.CR
  YM.TOTAL.CASH.UNP.1 = YM.CASH.UNPLEDGED
  YM1.TOTAL.CASH.UNP.1 = YM.TOTAL.CASH.UNP.1
  YM.TOTAL.CASH.UNP.1 = YM.METAL.UNPLEDGED
  IF NUM(YM1.TOTAL.CASH.UNP.1) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.UNP.1) = NUMERIC THEN
    YM1.TOTAL.CASH.UNP.1 = YM1.TOTAL.CASH.UNP.1 + YM.TOTAL.CASH.UNP.1
    IF YM1.TOTAL.CASH.UNP.1 = 0 THEN YM1.TOTAL.CASH.UNP.1 = ""
  END
  YM.TOTAL.CASH.UNP.1 = YM1.TOTAL.CASH.UNP.1
  YM.TOTAL.CASH.UNP.2 = YM.TOTAL.CASH.UNP.1
  YM1.TOTAL.CASH.UNP.2 = YM.TOTAL.CASH.UNP.2
  YM.TOTAL.CASH.UNP.2 = YM.DEPOSIT.UNPLEDGED
  IF NUM(YM1.TOTAL.CASH.UNP.2) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.UNP.2) = NUMERIC THEN
    YM1.TOTAL.CASH.UNP.2 = YM1.TOTAL.CASH.UNP.2 + YM.TOTAL.CASH.UNP.2
    IF YM1.TOTAL.CASH.UNP.2 = 0 THEN YM1.TOTAL.CASH.UNP.2 = ""
  END
  YM.TOTAL.CASH.UNP.2 = YM1.TOTAL.CASH.UNP.2
  YM.TOTAL.CASH.UNP.3 = YM.TOTAL.CASH.UNP.2
  YM1.TOTAL.CASH.UNP.3 = YM.TOTAL.CASH.UNP.3
  YM.TOTAL.CASH.UNP.3 = YM.FIDUCIARY.UNPLEDGED
  IF NUM(YM1.TOTAL.CASH.UNP.3) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.UNP.3) = NUMERIC THEN
    YM1.TOTAL.CASH.UNP.3 = YM1.TOTAL.CASH.UNP.3 + YM.TOTAL.CASH.UNP.3
    IF YM1.TOTAL.CASH.UNP.3 = 0 THEN YM1.TOTAL.CASH.UNP.3 = ""
  END
  YM.TOTAL.CASH.UNP.3 = YM1.TOTAL.CASH.UNP.3
  YM.TOTAL.CASH.UNP = YM.TOTAL.CASH.UNP.3
  YM1.TOTAL.CASH.UNP = YM.TOTAL.CASH.UNP
  YM.TOTAL.CASH.UNP = YM.CRED.DIFF.UNPLEDGED
  IF NUM(YM1.TOTAL.CASH.UNP) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.UNP) = NUMERIC THEN
    YM1.TOTAL.CASH.UNP = YM1.TOTAL.CASH.UNP + YM.TOTAL.CASH.UNP
    IF YM1.TOTAL.CASH.UNP = 0 THEN YM1.TOTAL.CASH.UNP = ""
  END
  YM.TOTAL.CASH.UNP = YM1.TOTAL.CASH.UNP
  YR.REC(46) = YM.TOTAL.CASH.UNP
  YM.TOTAL.CASH.PLG.1 = YM.CASH.PLEDGED
  YM1.TOTAL.CASH.PLG.1 = YM.TOTAL.CASH.PLG.1
  YM.TOTAL.CASH.PLG.1 = YM.METAL.PLEDGED
  IF NUM(YM1.TOTAL.CASH.PLG.1) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.PLG.1) = NUMERIC THEN
    YM1.TOTAL.CASH.PLG.1 = YM1.TOTAL.CASH.PLG.1 + YM.TOTAL.CASH.PLG.1
    IF YM1.TOTAL.CASH.PLG.1 = 0 THEN YM1.TOTAL.CASH.PLG.1 = ""
  END
  YM.TOTAL.CASH.PLG.1 = YM1.TOTAL.CASH.PLG.1
  YM.TOTAL.CASH.PLG.2 = YM.TOTAL.CASH.PLG.1
  YM1.TOTAL.CASH.PLG.2 = YM.TOTAL.CASH.PLG.2
  YM.TOTAL.CASH.PLG.2 = YM.DEPOSIT.PLEDGED
  IF NUM(YM1.TOTAL.CASH.PLG.2) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.PLG.2) = NUMERIC THEN
    YM1.TOTAL.CASH.PLG.2 = YM1.TOTAL.CASH.PLG.2 + YM.TOTAL.CASH.PLG.2
    IF YM1.TOTAL.CASH.PLG.2 = 0 THEN YM1.TOTAL.CASH.PLG.2 = ""
  END
  YM.TOTAL.CASH.PLG.2 = YM1.TOTAL.CASH.PLG.2
  YM.TOTAL.CASH.PLG.3 = YM.TOTAL.CASH.PLG.2
  YM1.TOTAL.CASH.PLG.3 = YM.TOTAL.CASH.PLG.3
  YM.TOTAL.CASH.PLG.3 = YM.FIDUCIARY.PLEDGED
  IF NUM(YM1.TOTAL.CASH.PLG.3) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.PLG.3) = NUMERIC THEN
    YM1.TOTAL.CASH.PLG.3 = YM1.TOTAL.CASH.PLG.3 + YM.TOTAL.CASH.PLG.3
    IF YM1.TOTAL.CASH.PLG.3 = 0 THEN YM1.TOTAL.CASH.PLG.3 = ""
  END
  YM.TOTAL.CASH.PLG.3 = YM1.TOTAL.CASH.PLG.3
  YM.TOTAL.CASH.PLG = YM.TOTAL.CASH.PLG.3
  YM1.TOTAL.CASH.PLG = YM.TOTAL.CASH.PLG
  YM.TOTAL.CASH.PLG = YM.CRED.DIFF.PLEDGED
  IF NUM(YM1.TOTAL.CASH.PLG) = NUMERIC THEN IF NUM(YM.TOTAL.CASH.PLG) = NUMERIC THEN
    YM1.TOTAL.CASH.PLG = YM1.TOTAL.CASH.PLG + YM.TOTAL.CASH.PLG
    IF YM1.TOTAL.CASH.PLG = 0 THEN YM1.TOTAL.CASH.PLG = ""
  END
  YM.TOTAL.CASH.PLG = YM1.TOTAL.CASH.PLG
  YR.REC(47) = YM.TOTAL.CASH.PLG
  YM.TEXT.21 = ""
  YR.REC(48) = YM.TEXT.21
  YM.TEXT.22 = ""
  YR.REC(49) = YM.TEXT.22
  YM.ARG.J1C = YM.CUSTOMER.GROUP
  YM167.GOSUB = YM.ARG.J1C
  YM.ARG.J2C = ""
  YM168.GOSUB = YM.ARG.J2C
  YM.ARG.J3C = "SC"
  YM169.GOSUB = YM.ARG.J3C
  YM.ARG.J4C = ""
  YM170.GOSUB = YM.ARG.J4C
  YM.ARG.J5C = YM.CURRENCY
  YM171.GOSUB = YM.ARG.J5C
  YM.ARG.J6C = ""
  YM172.GOSUB = YM.ARG.J6C
  YM.ARG.J7C = ""
  YM173.GOSUB = YM.ARG.J7C
  YM.ARG.J8C = ""
  YM174.GOSUB = YM.ARG.J8C
  CALL @RG.S.CUS.AL.POS (YM167.GOSUB, YM168.GOSUB, YM169.GOSUB, YM170.GOSUB, YM171.GOSUB, YM172.GOSUB, YM173.GOSUB, YM174.GOSUB)
  YM.ARG.J1C = YM167.GOSUB
  YM.ARG.J2C = YM168.GOSUB
  YM.ARG.J3C = YM169.GOSUB
  YM.ARG.J4C = YM170.GOSUB
  YM.ARG.J5C = YM171.GOSUB
  YM.ARG.J6C = YM172.GOSUB
  YM.ARG.J7C = YM173.GOSUB
  YM.ARG.J8C = YM174.GOSUB
  YM.SECURITIES.BALANCE = YM.ARG.J6C
  YR.REC(50) = YM.SECURITIES.BALANCE
  YM.SECURITIES.UNPLEDGED = YM.ARG.J7C
  YR.REC(51) = YM.SECURITIES.UNPLEDGED
  YM.SECURITIES.PLEDGED = YM.ARG.J8C
  YR.REC(52) = YM.SECURITIES.PLEDGED
  YM.TEXT.23 = ""
  YR.REC(53) = YM.TEXT.23
  YM.TEXT.24 = "CONTINGENT LIABILITIES"
  YR.REC(54) = YM.TEXT.24
  YM.TEXT.25 = "CONTINGENT ASSETS"
  YR.REC(55) = YM.TEXT.25
  YM.ARG.K1 = YM.CUSTOMER.GROUP
  YM181.GOSUB = YM.ARG.K1
  YM.ARG.K2 = "L"
  YM182.GOSUB = YM.ARG.K2
  YM.ARG.K3 = "LC"
  YM183.GOSUB = YM.ARG.K3
  YM.ARG.K4 = ""
  YM184.GOSUB = YM.ARG.K4
  YM.ARG.K5 = YM.CURRENCY
  YM185.GOSUB = YM.ARG.K5
  YM.ARG.K6 = ""
  YM186.GOSUB = YM.ARG.K6
  YM.ARG.K7 = ""
  YM187.GOSUB = YM.ARG.K7
  YM.ARG.K8 = ""
  YM188.GOSUB = YM.ARG.K8
  CALL @RG.S.CUS.AL.POS (YM181.GOSUB, YM182.GOSUB, YM183.GOSUB, YM184.GOSUB, YM185.GOSUB, YM186.GOSUB, YM187.GOSUB, YM188.GOSUB)
  YM.ARG.K1 = YM181.GOSUB
  YM.ARG.K2 = YM182.GOSUB
  YM.ARG.K3 = YM183.GOSUB
  YM.ARG.K4 = YM184.GOSUB
  YM.ARG.K5 = YM185.GOSUB
  YM.ARG.K6 = YM186.GOSUB
  YM.ARG.K7 = YM187.GOSUB
  YM.ARG.K8 = YM188.GOSUB
  YM.LC.BALANCE.DR = YM.ARG.K6
  YR.REC(56) = YM.LC.BALANCE.DR
  YM.ARG.L1 = YM.CUSTOMER.GROUP
  YM190.GOSUB = YM.ARG.L1
  YM.ARG.L2 = "A"
  YM191.GOSUB = YM.ARG.L2
  YM.ARG.L3 = "LC"
  YM192.GOSUB = YM.ARG.L3
  YM.ARG.L4 = ""
  YM193.GOSUB = YM.ARG.L4
  YM.ARG.L5 = YM.CURRENCY
  YM194.GOSUB = YM.ARG.L5
  YM.ARG.L6 = ""
  YM195.GOSUB = YM.ARG.L6
  YM.ARG.L7 = ""
  YM196.GOSUB = YM.ARG.L7
  YM.ARG.L8 = ""
  YM197.GOSUB = YM.ARG.L8
  CALL @RG.S.CUS.AL.POS (YM190.GOSUB, YM191.GOSUB, YM192.GOSUB, YM193.GOSUB, YM194.GOSUB, YM195.GOSUB, YM196.GOSUB, YM197.GOSUB)
  YM.ARG.L1 = YM190.GOSUB
  YM.ARG.L2 = YM191.GOSUB
  YM.ARG.L3 = YM192.GOSUB
  YM.ARG.L4 = YM193.GOSUB
  YM.ARG.L5 = YM194.GOSUB
  YM.ARG.L6 = YM195.GOSUB
  YM.ARG.L7 = YM196.GOSUB
  YM.ARG.L8 = YM197.GOSUB
  YM.LC.BALANCE.CR = YM.ARG.L6
  YR.REC(57) = YM.LC.BALANCE.CR
  YM.LC.UNPLEDGED = YM.ARG.L7
  YR.REC(58) = YM.LC.UNPLEDGED
  YM.LC.PLEDGED = YM.ARG.L8
  YR.REC(59) = YM.LC.PLEDGED
  YM.ARG.L1A = YM.CUSTOMER.GROUP
  YM201.GOSUB = YM.ARG.L1A
  YM.ARG.L2A = "L"
  YM202.GOSUB = YM.ARG.L2A
  YM.ARG.L3A = "MD"
  YM203.GOSUB = YM.ARG.L3A
  YM.ARG.L4A = "21050-21055"
  YM204.GOSUB = YM.ARG.L4A
  YM.ARG.L5A = YM.CURRENCY
  YM205.GOSUB = YM.ARG.L5A
  YM.ARG.L6A = ""
  YM206.GOSUB = YM.ARG.L6A
  YM.ARG.L7A = ""
  YM207.GOSUB = YM.ARG.L7A
  YM.ARG.L8A = ""
  YM208.GOSUB = YM.ARG.L8A
  CALL @RG.S.CUS.AL.POS (YM201.GOSUB, YM202.GOSUB, YM203.GOSUB, YM204.GOSUB, YM205.GOSUB, YM206.GOSUB, YM207.GOSUB, YM208.GOSUB)
  YM.ARG.L1A = YM201.GOSUB
  YM.ARG.L2A = YM202.GOSUB
  YM.ARG.L3A = YM203.GOSUB
  YM.ARG.L4A = YM204.GOSUB
  YM.ARG.L5A = YM205.GOSUB
  YM.ARG.L6A = YM206.GOSUB
  YM.ARG.L7A = YM207.GOSUB
  YM.ARG.L8A = YM208.GOSUB
  YM.GUARANTEES.GIVEN = YM.ARG.L6A
  YR.REC(60) = YM.GUARANTEES.GIVEN
  YM.ARG.L1B = YM.CUSTOMER.GROUP
  YM210.GOSUB = YM.ARG.L1B
  YM.ARG.L2B = "A"
  YM211.GOSUB = YM.ARG.L2B
  YM.ARG.L3B = "MD"
  YM212.GOSUB = YM.ARG.L3B
  YM.ARG.L4B = ""
  YM213.GOSUB = YM.ARG.L4B
  YM.ARG.L5B = YM.CURRENCY
  YM214.GOSUB = YM.ARG.L5B
  YM.ARG.L6B = ""
  YM215.GOSUB = YM.ARG.L6B
  YM.ARG.L7B = ""
  YM216.GOSUB = YM.ARG.L7B
  YM.ARG.L8B = ""
  YM217.GOSUB = YM.ARG.L8B
  CALL @RG.S.CUS.AL.POS (YM210.GOSUB, YM211.GOSUB, YM212.GOSUB, YM213.GOSUB, YM214.GOSUB, YM215.GOSUB, YM216.GOSUB, YM217.GOSUB)
  YM.ARG.L1B = YM210.GOSUB
  YM.ARG.L2B = YM211.GOSUB
  YM.ARG.L3B = YM212.GOSUB
  YM.ARG.L4B = YM213.GOSUB
  YM.ARG.L5B = YM214.GOSUB
  YM.ARG.L6B = YM215.GOSUB
  YM.ARG.L7B = YM216.GOSUB
  YM.ARG.L8B = YM217.GOSUB
  YM.GUARANTEES.RECEIVED = YM.ARG.L6B
  YR.REC(61) = YM.GUARANTEES.RECEIVED
  YM.GUARANTEES.UNPLEDGED = YM.ARG.L7B
  YR.REC(62) = YM.GUARANTEES.UNPLEDGED
  YM.GUARANTEES.PLEDGED = YM.ARG.L8B
  YR.REC(63) = YM.GUARANTEES.PLEDGED
  YM.ARG.L1C = YM.CUSTOMER.GROUP
  YM221.GOSUB = YM.ARG.L1C
  YM.ARG.L2C = "L"
  YM222.GOSUB = YM.ARG.L2C
  YM.ARG.L3C = "MD"
  YM223.GOSUB = YM.ARG.L3C
  YM.ARG.L4C = ""
  YM224.GOSUB = YM.ARG.L4C
  YM.ARG.L5C = YM.CURRENCY
  YM225.GOSUB = YM.ARG.L5C
  YM.ARG.L6C = ""
  YM226.GOSUB = YM.ARG.L6C
  YM.ARG.L7C = ""
  YM227.GOSUB = YM.ARG.L7C
  YM.ARG.L8C = ""
  YM228.GOSUB = YM.ARG.L8C
  CALL @RG.S.CUS.AL.POS (YM221.GOSUB, YM222.GOSUB, YM223.GOSUB, YM224.GOSUB, YM225.GOSUB, YM226.GOSUB, YM227.GOSUB, YM228.GOSUB)
  YM.ARG.L1C = YM221.GOSUB
  YM.ARG.L2C = YM222.GOSUB
  YM.ARG.L3C = YM223.GOSUB
  YM.ARG.L4C = YM224.GOSUB
  YM.ARG.L5C = YM225.GOSUB
  YM.ARG.L6C = YM226.GOSUB
  YM.ARG.L7C = YM227.GOSUB
  YM.ARG.L8C = YM228.GOSUB
  YM.CONTINGENT.OTHERS.DR = YM.ARG.L6C
  YR.REC(64) = YM.CONTINGENT.OTHERS.DR
  YM.ARG.L1D = YM.CUSTOMER.GROUP
  YM230.GOSUB = YM.ARG.L1D
  YM.ARG.L2D = "A"
  YM231.GOSUB = YM.ARG.L2D
  YM.ARG.L3D = "MD"
  YM232.GOSUB = YM.ARG.L3D
  YM.ARG.L4D = ""
  YM233.GOSUB = YM.ARG.L4D
  YM.ARG.L5D = YM.CURRENCY
  YM234.GOSUB = YM.ARG.L5D
  YM.ARG.L6D = ""
  YM235.GOSUB = YM.ARG.L6D
  YM.ARG.L7D = ""
  YM236.GOSUB = YM.ARG.L7D
  YM.ARG.L8D = ""
  YM237.GOSUB = YM.ARG.L8D
  CALL @RG.S.CUS.AL.POS (YM230.GOSUB, YM231.GOSUB, YM232.GOSUB, YM233.GOSUB, YM234.GOSUB, YM235.GOSUB, YM236.GOSUB, YM237.GOSUB)
  YM.ARG.L1D = YM230.GOSUB
  YM.ARG.L2D = YM231.GOSUB
  YM.ARG.L3D = YM232.GOSUB
  YM.ARG.L4D = YM233.GOSUB
  YM.ARG.L5D = YM234.GOSUB
  YM.ARG.L6D = YM235.GOSUB
  YM.ARG.L7D = YM236.GOSUB
  YM.ARG.L8D = YM237.GOSUB
  YM.CONTINGENT.OTHERS.CR = YM.ARG.L6D
  YR.REC(65) = YM.CONTINGENT.OTHERS.CR
  YM.CONTINGENT.UNPLEDGED = YM.ARG.L7D
  YR.REC(66) = YM.CONTINGENT.UNPLEDGED
  YM.CONTINGENT.PLEDGED = YM.ARG.L8D
  YR.REC(67) = YM.CONTINGENT.PLEDGED
  YM.TEXT.26 = ""
  YR.REC(68) = YM.TEXT.26
  YM.TEXT.27 = ""
  YR.REC(69) = YM.TEXT.27
  YM.TEXT.28 = "OTHERS"
  YR.REC(70) = YM.TEXT.28
  YM.ARG.L1E = YM.CUSTOMER.GROUP
  YM244.GOSUB = YM.ARG.L1E
  YM.ARG.L2E = "A"
  YM245.GOSUB = YM.ARG.L2E
  YM.ARG.L3E = "LD"
  YM246.GOSUB = YM.ARG.L3E
  YM.ARG.L4E = ""
  YM247.GOSUB = YM.ARG.L4E
  YM.ARG.L5E = YM.CURRENCY
  YM248.GOSUB = YM.ARG.L5E
  YM.ARG.L6E = ""
  YM249.GOSUB = YM.ARG.L6E
  YM.ARG.L7E = ""
  YM250.GOSUB = YM.ARG.L7E
  YM.ARG.L8E = ""
  YM251.GOSUB = YM.ARG.L8E
  CALL @RG.S.CUS.AL.POS (YM244.GOSUB, YM245.GOSUB, YM246.GOSUB, YM247.GOSUB, YM248.GOSUB, YM249.GOSUB, YM250.GOSUB, YM251.GOSUB)
  YM.ARG.L1E = YM244.GOSUB
  YM.ARG.L2E = YM245.GOSUB
  YM.ARG.L3E = YM246.GOSUB
  YM.ARG.L4E = YM247.GOSUB
  YM.ARG.L5E = YM248.GOSUB
  YM.ARG.L6E = YM249.GOSUB
  YM.ARG.L7E = YM250.GOSUB
  YM.ARG.L8E = YM251.GOSUB
  YM.OTHER.OTHERS = YM.ARG.L6E
  YR.REC(71) = YM.OTHER.OTHERS
  YM.OTHERS.UNPLEDGED = YM.ARG.L7E
  YR.REC(72) = YM.OTHERS.UNPLEDGED
  YM.OTHERS.PLEDGED = YM.ARG.L8E
  YR.REC(73) = YM.OTHERS.PLEDGED
  YM.ARG.L1F = YM.CUSTOMER.GROUP
  YM255.GOSUB = YM.ARG.L1F
  YM.ARG.L2F = "A"
  YM256.GOSUB = YM.ARG.L2F
  YM.ARG.L3F = "CO"
  YM257.GOSUB = YM.ARG.L3F
  YM.ARG.L4F = "LIAB"
  YM258.GOSUB = YM.ARG.L4F
  YM.ARG.L5F = YM.CURRENCY
  YM259.GOSUB = YM.ARG.L5F
  YM.ARG.L6F = ""
  YM260.GOSUB = YM.ARG.L6F
  YM.ARG.L7F = ""
  YM261.GOSUB = YM.ARG.L7F
  YM.ARG.L8F = ""
  YM262.GOSUB = YM.ARG.L8F
  CALL @RG.S.CUS.AL.POS (YM255.GOSUB, YM256.GOSUB, YM257.GOSUB, YM258.GOSUB, YM259.GOSUB, YM260.GOSUB, YM261.GOSUB, YM262.GOSUB)
  YM.ARG.L1F = YM255.GOSUB
  YM.ARG.L2F = YM256.GOSUB
  YM.ARG.L3F = YM257.GOSUB
  YM.ARG.L4F = YM258.GOSUB
  YM.ARG.L5F = YM259.GOSUB
  YM.ARG.L6F = YM260.GOSUB
  YM.ARG.L7F = YM261.GOSUB
  YM.ARG.L8F = YM262.GOSUB
  YM.COLLAT.REC.PLEDGED = YM.ARG.L8F
  YR.REC(74) = YM.COLLAT.REC.PLEDGED
  YM.ARG.L1G = YM.CUSTOMER.GROUP
  YM264.GOSUB = YM.ARG.L1G
  YM.ARG.L2G = "L"
  YM265.GOSUB = YM.ARG.L2G
  YM.ARG.L3G = "CO"
  YM266.GOSUB = YM.ARG.L3G
  YM.ARG.L4G = "LIAB"
  YM267.GOSUB = YM.ARG.L4G
  YM.ARG.L5G = YM.CURRENCY
  YM268.GOSUB = YM.ARG.L5G
  YM.ARG.L6G = ""
  YM269.GOSUB = YM.ARG.L6G
  YM.ARG.L7G = ""
  YM270.GOSUB = YM.ARG.L7G
  YM.ARG.L8G = ""
  YM271.GOSUB = YM.ARG.L8G
  CALL @RG.S.CUS.AL.POS (YM264.GOSUB, YM265.GOSUB, YM266.GOSUB, YM267.GOSUB, YM268.GOSUB, YM269.GOSUB, YM270.GOSUB, YM271.GOSUB)
  YM.ARG.L1G = YM264.GOSUB
  YM.ARG.L2G = YM265.GOSUB
  YM.ARG.L3G = YM266.GOSUB
  YM.ARG.L4G = YM267.GOSUB
  YM.ARG.L5G = YM268.GOSUB
  YM.ARG.L6G = YM269.GOSUB
  YM.ARG.L7G = YM270.GOSUB
  YM.ARG.L8G = YM271.GOSUB
  YM.COLLAT.GIVEN.PLEDGED = YM.ARG.L8G
  YR.REC(75) = YM.COLLAT.GIVEN.PLEDGED
  YM.TEXT.29 = ""
  YR.REC(76) = YM.TEXT.29
  YM.TOTAL.LIABILITIES.1 = YM.TOTAL.CASH.DR
  YM1.TOTAL.LIABILITIES.1 = YM.TOTAL.LIABILITIES.1
  YM.TOTAL.LIABILITIES.1 = YM.LC.BALANCE.DR
  IF NUM(YM1.TOTAL.LIABILITIES.1) = NUMERIC THEN IF NUM(YM.TOTAL.LIABILITIES.1) = NUMERIC THEN
    YM1.TOTAL.LIABILITIES.1 = YM1.TOTAL.LIABILITIES.1 + YM.TOTAL.LIABILITIES.1
    IF YM1.TOTAL.LIABILITIES.1 = 0 THEN YM1.TOTAL.LIABILITIES.1 = ""
  END
  YM.TOTAL.LIABILITIES.1 = YM1.TOTAL.LIABILITIES.1
  YM.TOTAL.LIABILITIES.2 = YM.TOTAL.LIABILITIES.1
  YM1.TOTAL.LIABILITIES.2 = YM.TOTAL.LIABILITIES.2
  YM.TOTAL.LIABILITIES.2 = YM.GUARANTEES.GIVEN
  IF NUM(YM1.TOTAL.LIABILITIES.2) = NUMERIC THEN IF NUM(YM.TOTAL.LIABILITIES.2) = NUMERIC THEN
    YM1.TOTAL.LIABILITIES.2 = YM1.TOTAL.LIABILITIES.2 + YM.TOTAL.LIABILITIES.2
    IF YM1.TOTAL.LIABILITIES.2 = 0 THEN YM1.TOTAL.LIABILITIES.2 = ""
  END
  YM.TOTAL.LIABILITIES.2 = YM1.TOTAL.LIABILITIES.2
  YM.TOTAL.LIABILITIES = YM.TOTAL.LIABILITIES.2
  YM1.TOTAL.LIABILITIES = YM.TOTAL.LIABILITIES
  YM.TOTAL.LIABILITIES = YM.CONTINGENT.OTHERS.DR
  IF NUM(YM1.TOTAL.LIABILITIES) = NUMERIC THEN IF NUM(YM.TOTAL.LIABILITIES) = NUMERIC THEN
    YM1.TOTAL.LIABILITIES = YM1.TOTAL.LIABILITIES + YM.TOTAL.LIABILITIES
    IF YM1.TOTAL.LIABILITIES = 0 THEN YM1.TOTAL.LIABILITIES = ""
  END
  YM.TOTAL.LIABILITIES = YM1.TOTAL.LIABILITIES
  YR.REC(77) = YM.TOTAL.LIABILITIES
  YM.TOTAL.ASSETS.1 = YM.TOTAL.CASH.CR
  YM1.TOTAL.ASSETS.1 = YM.TOTAL.ASSETS.1
  YM.TOTAL.ASSETS.1 = YM.SECURITIES.BALANCE
  IF NUM(YM1.TOTAL.ASSETS.1) = NUMERIC THEN IF NUM(YM.TOTAL.ASSETS.1) = NUMERIC THEN
    YM1.TOTAL.ASSETS.1 = YM1.TOTAL.ASSETS.1 + YM.TOTAL.ASSETS.1
    IF YM1.TOTAL.ASSETS.1 = 0 THEN YM1.TOTAL.ASSETS.1 = ""
  END
  YM.TOTAL.ASSETS.1 = YM1.TOTAL.ASSETS.1
  YM.TOTAL.ASSETS.2 = YM.TOTAL.ASSETS.1
  YM1.TOTAL.ASSETS.2 = YM.TOTAL.ASSETS.2
  YM.TOTAL.ASSETS.2 = YM.LC.BALANCE.CR
  IF NUM(YM1.TOTAL.ASSETS.2) = NUMERIC THEN IF NUM(YM.TOTAL.ASSETS.2) = NUMERIC THEN
    YM1.TOTAL.ASSETS.2 = YM1.TOTAL.ASSETS.2 + YM.TOTAL.ASSETS.2
    IF YM1.TOTAL.ASSETS.2 = 0 THEN YM1.TOTAL.ASSETS.2 = ""
  END
  YM.TOTAL.ASSETS.2 = YM1.TOTAL.ASSETS.2
  YM.TOTAL.ASSETS.3 = YM.TOTAL.ASSETS.2
  YM1.TOTAL.ASSETS.3 = YM.TOTAL.ASSETS.3
  YM.TOTAL.ASSETS.3 = YM.GUARANTEES.RECEIVED
  IF NUM(YM1.TOTAL.ASSETS.3) = NUMERIC THEN IF NUM(YM.TOTAL.ASSETS.3) = NUMERIC THEN
    YM1.TOTAL.ASSETS.3 = YM1.TOTAL.ASSETS.3 + YM.TOTAL.ASSETS.3
    IF YM1.TOTAL.ASSETS.3 = 0 THEN YM1.TOTAL.ASSETS.3 = ""
  END
  YM.TOTAL.ASSETS.3 = YM1.TOTAL.ASSETS.3
  YM.TOTAL.ASSETS.4 = YM.TOTAL.ASSETS.3
  YM1.TOTAL.ASSETS.4 = YM.TOTAL.ASSETS.4
  YM.TOTAL.ASSETS.4 = YM.CONTINGENT.OTHERS.CR
  IF NUM(YM1.TOTAL.ASSETS.4) = NUMERIC THEN IF NUM(YM.TOTAL.ASSETS.4) = NUMERIC THEN
    YM1.TOTAL.ASSETS.4 = YM1.TOTAL.ASSETS.4 + YM.TOTAL.ASSETS.4
    IF YM1.TOTAL.ASSETS.4 = 0 THEN YM1.TOTAL.ASSETS.4 = ""
  END
  YM.TOTAL.ASSETS.4 = YM1.TOTAL.ASSETS.4
  YM.TOTAL.ASSETS = YM.TOTAL.ASSETS.4
  YM1.TOTAL.ASSETS = YM.TOTAL.ASSETS
  YM.TOTAL.ASSETS = YM.OTHER.OTHERS
  IF NUM(YM1.TOTAL.ASSETS) = NUMERIC THEN IF NUM(YM.TOTAL.ASSETS) = NUMERIC THEN
    YM1.TOTAL.ASSETS = YM1.TOTAL.ASSETS + YM.TOTAL.ASSETS
    IF YM1.TOTAL.ASSETS = 0 THEN YM1.TOTAL.ASSETS = ""
  END
  YM.TOTAL.ASSETS = YM1.TOTAL.ASSETS
  YR.REC(78) = YM.TOTAL.ASSETS
  YM.TOTAL.UNPLEDGED.1 = YM.TOTAL.CASH.UNP
  YM1.TOTAL.UNPLEDGED.1 = YM.TOTAL.UNPLEDGED.1
  YM.TOTAL.UNPLEDGED.1 = YM.SECURITIES.UNPLEDGED
  IF NUM(YM1.TOTAL.UNPLEDGED.1) = NUMERIC THEN IF NUM(YM.TOTAL.UNPLEDGED.1) = NUMERIC THEN
    YM1.TOTAL.UNPLEDGED.1 = YM1.TOTAL.UNPLEDGED.1 + YM.TOTAL.UNPLEDGED.1
    IF YM1.TOTAL.UNPLEDGED.1 = 0 THEN YM1.TOTAL.UNPLEDGED.1 = ""
  END
  YM.TOTAL.UNPLEDGED.1 = YM1.TOTAL.UNPLEDGED.1
  YM.TOTAL.UNPLEDGED.2 = YM.TOTAL.UNPLEDGED.1
  YM1.TOTAL.UNPLEDGED.2 = YM.TOTAL.UNPLEDGED.2
  YM.TOTAL.UNPLEDGED.2 = YM.LC.UNPLEDGED
  IF NUM(YM1.TOTAL.UNPLEDGED.2) = NUMERIC THEN IF NUM(YM.TOTAL.UNPLEDGED.2) = NUMERIC THEN
    YM1.TOTAL.UNPLEDGED.2 = YM1.TOTAL.UNPLEDGED.2 + YM.TOTAL.UNPLEDGED.2
    IF YM1.TOTAL.UNPLEDGED.2 = 0 THEN YM1.TOTAL.UNPLEDGED.2 = ""
  END
  YM.TOTAL.UNPLEDGED.2 = YM1.TOTAL.UNPLEDGED.2
  YM.TOTAL.UNPLEDGED.3 = YM.TOTAL.UNPLEDGED.2
  YM1.TOTAL.UNPLEDGED.3 = YM.TOTAL.UNPLEDGED.3
  YM.TOTAL.UNPLEDGED.3 = YM.GUARANTEES.UNPLEDGED
  IF NUM(YM1.TOTAL.UNPLEDGED.3) = NUMERIC THEN IF NUM(YM.TOTAL.UNPLEDGED.3) = NUMERIC THEN
    YM1.TOTAL.UNPLEDGED.3 = YM1.TOTAL.UNPLEDGED.3 + YM.TOTAL.UNPLEDGED.3
    IF YM1.TOTAL.UNPLEDGED.3 = 0 THEN YM1.TOTAL.UNPLEDGED.3 = ""
  END
  YM.TOTAL.UNPLEDGED.3 = YM1.TOTAL.UNPLEDGED.3
  YM.TOTAL.UNPLEDGED.4 = YM.TOTAL.UNPLEDGED.3
  YM1.TOTAL.UNPLEDGED.4 = YM.TOTAL.UNPLEDGED.4
  YM.TOTAL.UNPLEDGED.4 = YM.CONTINGENT.UNPLEDGED
  IF NUM(YM1.TOTAL.UNPLEDGED.4) = NUMERIC THEN IF NUM(YM.TOTAL.UNPLEDGED.4) = NUMERIC THEN
    YM1.TOTAL.UNPLEDGED.4 = YM1.TOTAL.UNPLEDGED.4 + YM.TOTAL.UNPLEDGED.4
    IF YM1.TOTAL.UNPLEDGED.4 = 0 THEN YM1.TOTAL.UNPLEDGED.4 = ""
  END
  YM.TOTAL.UNPLEDGED.4 = YM1.TOTAL.UNPLEDGED.4
  YM.TOTAL.UNPLEDGED = YM.TOTAL.UNPLEDGED.4
  YM1.TOTAL.UNPLEDGED = YM.TOTAL.UNPLEDGED
  YM.TOTAL.UNPLEDGED = YM.OTHERS.UNPLEDGED
  IF NUM(YM1.TOTAL.UNPLEDGED) = NUMERIC THEN IF NUM(YM.TOTAL.UNPLEDGED) = NUMERIC THEN
    YM1.TOTAL.UNPLEDGED = YM1.TOTAL.UNPLEDGED + YM.TOTAL.UNPLEDGED
    IF YM1.TOTAL.UNPLEDGED = 0 THEN YM1.TOTAL.UNPLEDGED = ""
  END
  YM.TOTAL.UNPLEDGED = YM1.TOTAL.UNPLEDGED
  YR.REC(79) = YM.TOTAL.UNPLEDGED
  YM.TOTAL.PLEDGED.1 = YM.TOTAL.CASH.PLG
  YM1.TOTAL.PLEDGED.1 = YM.TOTAL.PLEDGED.1
  YM.TOTAL.PLEDGED.1 = YM.SECURITIES.PLEDGED
  IF NUM(YM1.TOTAL.PLEDGED.1) = NUMERIC THEN IF NUM(YM.TOTAL.PLEDGED.1) = NUMERIC THEN
    YM1.TOTAL.PLEDGED.1 = YM1.TOTAL.PLEDGED.1 + YM.TOTAL.PLEDGED.1
    IF YM1.TOTAL.PLEDGED.1 = 0 THEN YM1.TOTAL.PLEDGED.1 = ""
  END
  YM.TOTAL.PLEDGED.1 = YM1.TOTAL.PLEDGED.1
  YM.TOTAL.PLEDGED.2 = YM.TOTAL.PLEDGED.1
  YM1.TOTAL.PLEDGED.2 = YM.TOTAL.PLEDGED.2
  YM.TOTAL.PLEDGED.2 = YM.LC.PLEDGED
  IF NUM(YM1.TOTAL.PLEDGED.2) = NUMERIC THEN IF NUM(YM.TOTAL.PLEDGED.2) = NUMERIC THEN
    YM1.TOTAL.PLEDGED.2 = YM1.TOTAL.PLEDGED.2 + YM.TOTAL.PLEDGED.2
    IF YM1.TOTAL.PLEDGED.2 = 0 THEN YM1.TOTAL.PLEDGED.2 = ""
  END
  YM.TOTAL.PLEDGED.2 = YM1.TOTAL.PLEDGED.2
  YM.TOTAL.PLEDGED.3 = YM.TOTAL.PLEDGED.2
  YM1.TOTAL.PLEDGED.3 = YM.TOTAL.PLEDGED.3
  YM.TOTAL.PLEDGED.3 = YM.GUARANTEES.PLEDGED
  IF NUM(YM1.TOTAL.PLEDGED.3) = NUMERIC THEN IF NUM(YM.TOTAL.PLEDGED.3) = NUMERIC THEN
    YM1.TOTAL.PLEDGED.3 = YM1.TOTAL.PLEDGED.3 + YM.TOTAL.PLEDGED.3
    IF YM1.TOTAL.PLEDGED.3 = 0 THEN YM1.TOTAL.PLEDGED.3 = ""
  END
  YM.TOTAL.PLEDGED.3 = YM1.TOTAL.PLEDGED.3
  YM.TOTAL.PLEDGED.4 = YM.TOTAL.PLEDGED.3
  YM1.TOTAL.PLEDGED.4 = YM.TOTAL.PLEDGED.4
  YM.TOTAL.PLEDGED.4 = YM.CONTINGENT.PLEDGED
  IF NUM(YM1.TOTAL.PLEDGED.4) = NUMERIC THEN IF NUM(YM.TOTAL.PLEDGED.4) = NUMERIC THEN
    YM1.TOTAL.PLEDGED.4 = YM1.TOTAL.PLEDGED.4 + YM.TOTAL.PLEDGED.4
    IF YM1.TOTAL.PLEDGED.4 = 0 THEN YM1.TOTAL.PLEDGED.4 = ""
  END
  YM.TOTAL.PLEDGED.4 = YM1.TOTAL.PLEDGED.4
  YM.TOTAL.PLEDGED.5 = YM.TOTAL.PLEDGED.4
  YM1.TOTAL.PLEDGED.5 = YM.TOTAL.PLEDGED.5
  YM.TOTAL.PLEDGED.5 = YM.OTHERS.PLEDGED
  IF NUM(YM1.TOTAL.PLEDGED.5) = NUMERIC THEN IF NUM(YM.TOTAL.PLEDGED.5) = NUMERIC THEN
    YM1.TOTAL.PLEDGED.5 = YM1.TOTAL.PLEDGED.5 + YM.TOTAL.PLEDGED.5
    IF YM1.TOTAL.PLEDGED.5 = 0 THEN YM1.TOTAL.PLEDGED.5 = ""
  END
  YM.TOTAL.PLEDGED.5 = YM1.TOTAL.PLEDGED.5
  YM.TOTAL.PLEDGED.6 = YM.TOTAL.PLEDGED.5
  YM1.TOTAL.PLEDGED.6 = YM.TOTAL.PLEDGED.6
  YM.TOTAL.PLEDGED.6 = YM.COLLAT.REC.PLEDGED
  IF NUM(YM1.TOTAL.PLEDGED.6) = NUMERIC THEN IF NUM(YM.TOTAL.PLEDGED.6) = NUMERIC THEN
    YM1.TOTAL.PLEDGED.6 = YM1.TOTAL.PLEDGED.6 + YM.TOTAL.PLEDGED.6
    IF YM1.TOTAL.PLEDGED.6 = 0 THEN YM1.TOTAL.PLEDGED.6 = ""
  END
  YM.TOTAL.PLEDGED.6 = YM1.TOTAL.PLEDGED.6
  YM.TOTAL.PLEDGED = YM.TOTAL.PLEDGED.6
  YM1.TOTAL.PLEDGED = YM.TOTAL.PLEDGED
  YM.TOTAL.PLEDGED = YM.COLLAT.GIVEN.PLEDGED
  IF NUM(YM1.TOTAL.PLEDGED) = NUMERIC THEN IF NUM(YM.TOTAL.PLEDGED) = NUMERIC THEN
    YM1.TOTAL.PLEDGED = YM1.TOTAL.PLEDGED + YM.TOTAL.PLEDGED
    IF YM1.TOTAL.PLEDGED = 0 THEN YM1.TOTAL.PLEDGED = ""
  END
  YM.TOTAL.PLEDGED = YM1.TOTAL.PLEDGED
  YR.REC(80) = YM.TOTAL.PLEDGED
  YM.TEXT.30 = ""
  YR.REC(81) = YM.TEXT.30
  YM.TEXT.31 = "DERIVED LIABILITIES"
  YR.REC(82) = YM.TEXT.31
  YM.TEXT.32 = "DERIVED ASSETS"
  YR.REC(83) = YM.TEXT.32
  YM.ARG.M1 = YM.CUSTOMER.GROUP
  YM297.GOSUB = YM.ARG.M1
  YM.ARG.M2 = "L"
  YM298.GOSUB = YM.ARG.M2
  YM.ARG.M3 = "FX"
  YM299.GOSUB = YM.ARG.M3
  YM.ARG.M4 = ""
  YM300.GOSUB = YM.ARG.M4
  YM.ARG.M5 = YM.CURRENCY
  YM301.GOSUB = YM.ARG.M5
  YM.ARG.M6 = ""
  YM302.GOSUB = YM.ARG.M6
  YM.ARG.M7 = ""
  YM303.GOSUB = YM.ARG.M7
  YM.ARG.M8 = ""
  YM304.GOSUB = YM.ARG.M8
  CALL @RG.S.CUS.AL.POS (YM297.GOSUB, YM298.GOSUB, YM299.GOSUB, YM300.GOSUB, YM301.GOSUB, YM302.GOSUB, YM303.GOSUB, YM304.GOSUB)
  YM.ARG.M1 = YM297.GOSUB
  YM.ARG.M2 = YM298.GOSUB
  YM.ARG.M3 = YM299.GOSUB
  YM.ARG.M4 = YM300.GOSUB
  YM.ARG.M5 = YM301.GOSUB
  YM.ARG.M6 = YM302.GOSUB
  YM.ARG.M7 = YM303.GOSUB
  YM.ARG.M8 = YM304.GOSUB
  YM.FOREX.LIABILITIES = YM.ARG.M6
  YR.REC(84) = YM.FOREX.LIABILITIES
  YM.ARG.N1 = YM.CUSTOMER.GROUP
  YM306.GOSUB = YM.ARG.N1
  YM.ARG.N2 = "A"
  YM307.GOSUB = YM.ARG.N2
  YM.ARG.N3 = "FX"
  YM308.GOSUB = YM.ARG.N3
  YM.ARG.N4 = ""
  YM309.GOSUB = YM.ARG.N4
  YM.ARG.N5 = YM.CURRENCY
  YM310.GOSUB = YM.ARG.N5
  YM.ARG.N6 = ""
  YM311.GOSUB = YM.ARG.N6
  YM.ARG.N7 = ""
  YM312.GOSUB = YM.ARG.N7
  YM.ARG.N8 = ""
  YM313.GOSUB = YM.ARG.N8
  CALL @RG.S.CUS.AL.POS (YM306.GOSUB, YM307.GOSUB, YM308.GOSUB, YM309.GOSUB, YM310.GOSUB, YM311.GOSUB, YM312.GOSUB, YM313.GOSUB)
  YM.ARG.N1 = YM306.GOSUB
  YM.ARG.N2 = YM307.GOSUB
  YM.ARG.N3 = YM308.GOSUB
  YM.ARG.N4 = YM309.GOSUB
  YM.ARG.N5 = YM310.GOSUB
  YM.ARG.N6 = YM311.GOSUB
  YM.ARG.N7 = YM312.GOSUB
  YM.ARG.N8 = YM313.GOSUB
  YM.FOREX.ASSETS = YM.ARG.N6
  YR.REC(85) = YM.FOREX.ASSETS
  YM.ARG.N1A = YM.CUSTOMER.GROUP
  YM315.GOSUB = YM.ARG.N1A
  YM.ARG.N2A = "L"
  YM316.GOSUB = YM.ARG.N2A
  YM.ARG.N3A = "LD"
  YM317.GOSUB = YM.ARG.N3A
  YM.ARG.N4A = ""
  YM318.GOSUB = YM.ARG.N4A
  YM.ARG.N5A = YM.CURRENCY
  YM319.GOSUB = YM.ARG.N5A
  YM.ARG.N6A = ""
  YM320.GOSUB = YM.ARG.N6A
  YM.ARG.N7A = ""
  YM321.GOSUB = YM.ARG.N7A
  YM.ARG.N8A = ""
  YM322.GOSUB = YM.ARG.N8A
  CALL @RG.S.CUS.AL.POS (YM315.GOSUB, YM316.GOSUB, YM317.GOSUB, YM318.GOSUB, YM319.GOSUB, YM320.GOSUB, YM321.GOSUB, YM322.GOSUB)
  YM.ARG.N1A = YM315.GOSUB
  YM.ARG.N2A = YM316.GOSUB
  YM.ARG.N3A = YM317.GOSUB
  YM.ARG.N4A = YM318.GOSUB
  YM.ARG.N5A = YM319.GOSUB
  YM.ARG.N6A = YM320.GOSUB
  YM.ARG.N7A = YM321.GOSUB
  YM.ARG.N8A = YM322.GOSUB
  YM.IRS.LIABILITIES = YM.ARG.N6A
  YR.REC(86) = YM.IRS.LIABILITIES
  YM.ARG.N1B = YM.CUSTOMER.GROUP
  YM324.GOSUB = YM.ARG.N1B
  YM.ARG.N2B = "A"
  YM325.GOSUB = YM.ARG.N2B
  YM.ARG.N3B = "LD"
  YM326.GOSUB = YM.ARG.N3B
  YM.ARG.N4B = ""
  YM327.GOSUB = YM.ARG.N4B
  YM.ARG.N5B = YM.CURRENCY
  YM328.GOSUB = YM.ARG.N5B
  YM.ARG.N6B = ""
  YM329.GOSUB = YM.ARG.N6B
  YM.ARG.N7B = ""
  YM330.GOSUB = YM.ARG.N7B
  YM.ARG.N8B = ""
  YM331.GOSUB = YM.ARG.N8B
  CALL @RG.S.CUS.AL.POS (YM324.GOSUB, YM325.GOSUB, YM326.GOSUB, YM327.GOSUB, YM328.GOSUB, YM329.GOSUB, YM330.GOSUB, YM331.GOSUB)
  YM.ARG.N1B = YM324.GOSUB
  YM.ARG.N2B = YM325.GOSUB
  YM.ARG.N3B = YM326.GOSUB
  YM.ARG.N4B = YM327.GOSUB
  YM.ARG.N5B = YM328.GOSUB
  YM.ARG.N6B = YM329.GOSUB
  YM.ARG.N7B = YM330.GOSUB
  YM.ARG.N8B = YM331.GOSUB
  YM.IRS.ASSETS = YM.ARG.N6B
  YR.REC(87) = YM.IRS.ASSETS
  YM.ARG.N1C = YM.CUSTOMER.GROUP
  YM333.GOSUB = YM.ARG.N1C
  YM.ARG.N2C = "L"
  YM334.GOSUB = YM.ARG.N2C
  YM.ARG.N3C = "FR"
  YM335.GOSUB = YM.ARG.N3C
  YM.ARG.N4C = ""
  YM336.GOSUB = YM.ARG.N4C
  YM.ARG.N5C = YM.CURRENCY
  YM337.GOSUB = YM.ARG.N5C
  YM.ARG.N6C = ""
  YM338.GOSUB = YM.ARG.N6C
  YM.ARG.N7C = ""
  YM339.GOSUB = YM.ARG.N7C
  YM.ARG.N8C = ""
  YM340.GOSUB = YM.ARG.N8C
  CALL @RG.S.CUS.AL.POS (YM333.GOSUB, YM334.GOSUB, YM335.GOSUB, YM336.GOSUB, YM337.GOSUB, YM338.GOSUB, YM339.GOSUB, YM340.GOSUB)
  YM.ARG.N1C = YM333.GOSUB
  YM.ARG.N2C = YM334.GOSUB
  YM.ARG.N3C = YM335.GOSUB
  YM.ARG.N4C = YM336.GOSUB
  YM.ARG.N5C = YM337.GOSUB
  YM.ARG.N6C = YM338.GOSUB
  YM.ARG.N7C = YM339.GOSUB
  YM.ARG.N8C = YM340.GOSUB
  YM.FRA.LIABILITIES = YM.ARG.N6C
  YR.REC(88) = YM.FRA.LIABILITIES
  YM.ARG.N1D = YM.CUSTOMER.GROUP
  YM342.GOSUB = YM.ARG.N1D
  YM.ARG.N2D = "A"
  YM343.GOSUB = YM.ARG.N2D
  YM.ARG.N3D = "FR"
  YM344.GOSUB = YM.ARG.N3D
  YM.ARG.N4D = ""
  YM345.GOSUB = YM.ARG.N4D
  YM.ARG.N5D = YM.CURRENCY
  YM346.GOSUB = YM.ARG.N5D
  YM.ARG.N6D = ""
  YM347.GOSUB = YM.ARG.N6D
  YM.ARG.N7D = ""
  YM348.GOSUB = YM.ARG.N7D
  YM.ARG.N8D = ""
  YM349.GOSUB = YM.ARG.N8D
  CALL @RG.S.CUS.AL.POS (YM342.GOSUB, YM343.GOSUB, YM344.GOSUB, YM345.GOSUB, YM346.GOSUB, YM347.GOSUB, YM348.GOSUB, YM349.GOSUB)
  YM.ARG.N1D = YM342.GOSUB
  YM.ARG.N2D = YM343.GOSUB
  YM.ARG.N3D = YM344.GOSUB
  YM.ARG.N4D = YM345.GOSUB
  YM.ARG.N5D = YM346.GOSUB
  YM.ARG.N6D = YM347.GOSUB
  YM.ARG.N7D = YM348.GOSUB
  YM.ARG.N8D = YM349.GOSUB
  YM.FRA.ASSETS = YM.ARG.N6D
  YR.REC(89) = YM.FRA.ASSETS
  YM.TEXT.33 = ""
  YR.REC(90) = YM.TEXT.33
  YM.TEXT.34 = "MEMORANDUM LIABILITIES"
  YR.REC(91) = YM.TEXT.34
  YM.TEXT.35 = "MEMORANDUM ASSETS"
  YR.REC(92) = YM.TEXT.35
  YM.ARG.N1E = YM.CUSTOMER.GROUP
  YM354.GOSUB = YM.ARG.N1E
  YM.ARG.N2E = "L"
  YM355.GOSUB = YM.ARG.N2E
  YM.ARG.N3E = "MD"
  YM356.GOSUB = YM.ARG.N3E
  YM.ARG.N4E = ""
  YM357.GOSUB = YM.ARG.N4E
  YM.ARG.N5E = YM.CURRENCY
  YM358.GOSUB = YM.ARG.N5E
  YM.ARG.N6E = ""
  YM359.GOSUB = YM.ARG.N6E
  YM.ARG.N7E = ""
  YM360.GOSUB = YM.ARG.N7E
  YM.ARG.N8E = ""
  YM361.GOSUB = YM.ARG.N8E
  CALL @RG.S.CUS.AL.POS (YM354.GOSUB, YM355.GOSUB, YM356.GOSUB, YM357.GOSUB, YM358.GOSUB, YM359.GOSUB, YM360.GOSUB, YM361.GOSUB)
  YM.ARG.N1E = YM354.GOSUB
  YM.ARG.N2E = YM355.GOSUB
  YM.ARG.N3E = YM356.GOSUB
  YM.ARG.N4E = YM357.GOSUB
  YM.ARG.N5E = YM358.GOSUB
  YM.ARG.N6E = YM359.GOSUB
  YM.ARG.N7E = YM360.GOSUB
  YM.ARG.N8E = YM361.GOSUB
  YM.DISCOUNTED.BILLS.L = YM.ARG.N6E
  YR.REC(93) = YM.DISCOUNTED.BILLS.L
  YM.ARG.N1F = YM.CUSTOMER.GROUP
  YM363.GOSUB = YM.ARG.N1F
  YM.ARG.N2F = "A"
  YM364.GOSUB = YM.ARG.N2F
  YM.ARG.N3F = "MD"
  YM365.GOSUB = YM.ARG.N3F
  YM.ARG.N4F = ""
  YM366.GOSUB = YM.ARG.N4F
  YM.ARG.N5F = YM.CURRENCY
  YM367.GOSUB = YM.ARG.N5F
  YM.ARG.N6F = ""
  YM368.GOSUB = YM.ARG.N6F
  YM.ARG.N7F = ""
  YM369.GOSUB = YM.ARG.N7F
  YM.ARG.N8F = ""
  YM370.GOSUB = YM.ARG.N8F
  CALL @RG.S.CUS.AL.POS (YM363.GOSUB, YM364.GOSUB, YM365.GOSUB, YM366.GOSUB, YM367.GOSUB, YM368.GOSUB, YM369.GOSUB, YM370.GOSUB)
  YM.ARG.N1F = YM363.GOSUB
  YM.ARG.N2F = YM364.GOSUB
  YM.ARG.N3F = YM365.GOSUB
  YM.ARG.N4F = YM366.GOSUB
  YM.ARG.N5F = YM367.GOSUB
  YM.ARG.N6F = YM368.GOSUB
  YM.ARG.N7F = YM369.GOSUB
  YM.ARG.N8F = YM370.GOSUB
  YM.DISCOUNTED.BILLS.A = YM.ARG.N6F
  YR.REC(94) = YM.DISCOUNTED.BILLS.A
  YM.ARG.N1G = YM.CUSTOMER.GROUP
  YM372.GOSUB = YM.ARG.N1G
  YM.ARG.N2G = "L"
  YM373.GOSUB = YM.ARG.N2G
  YM.ARG.N3G = "MD"
  YM374.GOSUB = YM.ARG.N3G
  YM.ARG.N4G = ""
  YM375.GOSUB = YM.ARG.N4G
  YM.ARG.N5G = YM.CURRENCY
  YM376.GOSUB = YM.ARG.N5G
  YM.ARG.N6G = ""
  YM377.GOSUB = YM.ARG.N6G
  YM.ARG.N7G = ""
  YM378.GOSUB = YM.ARG.N7G
  YM.ARG.N8G = ""
  YM379.GOSUB = YM.ARG.N8G
  CALL @RG.S.CUS.AL.POS (YM372.GOSUB, YM373.GOSUB, YM374.GOSUB, YM375.GOSUB, YM376.GOSUB, YM377.GOSUB, YM378.GOSUB, YM379.GOSUB)
  YM.ARG.N1G = YM372.GOSUB
  YM.ARG.N2G = YM373.GOSUB
  YM.ARG.N3G = YM374.GOSUB
  YM.ARG.N4G = YM375.GOSUB
  YM.ARG.N5G = YM376.GOSUB
  YM.ARG.N6G = YM377.GOSUB
  YM.ARG.N7G = YM378.GOSUB
  YM.ARG.N8G = YM379.GOSUB
  YM.DOCUMENTS.L = YM.ARG.N6G
  YR.REC(95) = YM.DOCUMENTS.L
  YM.ARG.N1H = YM.CUSTOMER.GROUP
  YM381.GOSUB = YM.ARG.N1H
  YM.ARG.N2H = "A"
  YM382.GOSUB = YM.ARG.N2H
  YM.ARG.N3H = "MD"
  YM383.GOSUB = YM.ARG.N3H
  YM.ARG.N4H = ""
  YM384.GOSUB = YM.ARG.N4H
  YM.ARG.N5H = YM.CURRENCY
  YM385.GOSUB = YM.ARG.N5H
  YM.ARG.N6H = ""
  YM386.GOSUB = YM.ARG.N6H
  YM.ARG.N7H = ""
  YM387.GOSUB = YM.ARG.N7H
  YM.ARG.N8H = ""
  YM388.GOSUB = YM.ARG.N8H
  CALL @RG.S.CUS.AL.POS (YM381.GOSUB, YM382.GOSUB, YM383.GOSUB, YM384.GOSUB, YM385.GOSUB, YM386.GOSUB, YM387.GOSUB, YM388.GOSUB)
  YM.ARG.N1H = YM381.GOSUB
  YM.ARG.N2H = YM382.GOSUB
  YM.ARG.N3H = YM383.GOSUB
  YM.ARG.N4H = YM384.GOSUB
  YM.ARG.N5H = YM385.GOSUB
  YM.ARG.N6H = YM386.GOSUB
  YM.ARG.N7H = YM387.GOSUB
  YM.ARG.N8H = YM388.GOSUB
  YM.DOCUMENTS.A = YM.ARG.N6H
  YR.REC(96) = YM.DOCUMENTS.A
  YM.ARG.N1I = YM.CUSTOMER.GROUP
  YM390.GOSUB = YM.ARG.N1I
  YM.ARG.N2I = "L"
  YM391.GOSUB = YM.ARG.N2I
  YM.ARG.N3I = "MD"
  YM392.GOSUB = YM.ARG.N3I
  YM.ARG.N4I = ""
  YM393.GOSUB = YM.ARG.N4I
  YM.ARG.N5I = YM.CURRENCY
  YM394.GOSUB = YM.ARG.N5I
  YM.ARG.N6I = ""
  YM395.GOSUB = YM.ARG.N6I
  YM.ARG.N7I = ""
  YM396.GOSUB = YM.ARG.N7I
  YM.ARG.N8I = ""
  YM397.GOSUB = YM.ARG.N8I
  CALL @RG.S.CUS.AL.POS (YM390.GOSUB, YM391.GOSUB, YM392.GOSUB, YM393.GOSUB, YM394.GOSUB, YM395.GOSUB, YM396.GOSUB, YM397.GOSUB)
  YM.ARG.N1I = YM390.GOSUB
  YM.ARG.N2I = YM391.GOSUB
  YM.ARG.N3I = YM392.GOSUB
  YM.ARG.N4I = YM393.GOSUB
  YM.ARG.N5I = YM394.GOSUB
  YM.ARG.N6I = YM395.GOSUB
  YM.ARG.N7I = YM396.GOSUB
  YM.ARG.N8I = YM397.GOSUB
  YM.GOODS.L = YM.ARG.N6I
  YR.REC(97) = YM.GOODS.L
  YM.ARG.N1J = YM.CUSTOMER.GROUP
  YM399.GOSUB = YM.ARG.N1J
  YM.ARG.N2J = "A"
  YM400.GOSUB = YM.ARG.N2J
  YM.ARG.N3J = "MD"
  YM401.GOSUB = YM.ARG.N3J
  YM.ARG.N4J = ""
  YM402.GOSUB = YM.ARG.N4J
  YM.ARG.N5J = YM.CURRENCY
  YM403.GOSUB = YM.ARG.N5J
  YM.ARG.N6J = ""
  YM404.GOSUB = YM.ARG.N6J
  YM.ARG.N7J = ""
  YM405.GOSUB = YM.ARG.N7J
  YM.ARG.N8J = ""
  YM406.GOSUB = YM.ARG.N8J
  CALL @RG.S.CUS.AL.POS (YM399.GOSUB, YM400.GOSUB, YM401.GOSUB, YM402.GOSUB, YM403.GOSUB, YM404.GOSUB, YM405.GOSUB, YM406.GOSUB)
  YM.ARG.N1J = YM399.GOSUB
  YM.ARG.N2J = YM400.GOSUB
  YM.ARG.N3J = YM401.GOSUB
  YM.ARG.N4J = YM402.GOSUB
  YM.ARG.N5J = YM403.GOSUB
  YM.ARG.N6J = YM404.GOSUB
  YM.ARG.N7J = YM405.GOSUB
  YM.ARG.N8J = YM406.GOSUB
  YM.GOODS.A = YM.ARG.N6J
  YR.REC(98) = YM.GOODS.A
  YM.TEXT.36 = ""
  YR.REC(99) = YM.TEXT.36
  YM.TEXT.37 = "L I M I T"
  YR.REC(100) = YM.TEXT.37
  YM.TEXT.38 = "C O L L A T E R A L"
  YR.REC(101) = YM.TEXT.38
  YM.TEXT.39 = "NAME"
  YR.REC(102) = YM.TEXT.39
  YM.TEXT.40 = "ALLOWED"
  YR.REC(103) = YM.TEXT.40
  YM.TEXT.41 = "ON-LINE"
  YR.REC(104) = YM.TEXT.41
  YM.TEXT.42 = "USED"
  YR.REC(105) = YM.TEXT.42
  YM.TEXT.43 = "AVAILABLE"
  YR.REC(106) = YM.TEXT.43
  YM.TEXT.44 = "UNSECURED"
  YR.REC(107) = YM.TEXT.44
  YM.TEXT.45 = "COLLATERAL"
  YR.REC(108) = YM.TEXT.45
  YM.TEXT.46 = "USED"
  YR.REC(109) = YM.TEXT.46
  YM.TEXT.47 = "LIMIT"
  YR.REC(110) = YM.TEXT.47
  YM.TEXT.48 = "LIMIT"
  YR.REC(111) = YM.TEXT.48
  YM.TEXT.49 = "AMOUNT"
  YR.REC(112) = YM.TEXT.49
  YM.TEXT.50 = "AMOUNT"
  YR.REC(113) = YM.TEXT.50
  YM.TEXT.51 = "AMOUNT"
  YR.REC(114) = YM.TEXT.51
  YM.TEXT.52 = "CODE"
  YR.REC(115) = YM.TEXT.52
  YM.TEXT.53 = "AMOUNT"
  YR.REC(116) = YM.TEXT.53
  YM.TEXT.54 = ""
  YR.REC(117) = YM.TEXT.54
  YM.ARG.O1 = YM.CUSTOMER.NO
  YM427.GOSUB = YM.ARG.O1
  YM.ARG.O2 = ""
  YM428.GOSUB = YM.ARG.O2
  CALL @RG.S.LIMIT.LINE.IDS (YM427.GOSUB, YM428.GOSUB)
  YM.ARG.O1 = YM427.GOSUB
  YM.ARG.O2 = YM428.GOSUB
  YM.ARG.O1A = YM.ARG.O2
  YM429.GOSUB = YM.ARG.O1A
  YM.ARG.O2A = ",FX,TB,BD"
  YM430.GOSUB = YM.ARG.O2A
  YM.ARG.O3A = ""
  YM431.GOSUB = YM.ARG.O3A
  CALL @RG.S.LIMIT.ID.TYPES (YM429.GOSUB, YM430.GOSUB, YM431.GOSUB)
  YM.ARG.O1A = YM429.GOSUB
  YM.ARG.O2A = YM430.GOSUB
  YM.ARG.O3A = YM431.GOSUB
  YM.LIMIT.ID = YM.ARG.O3A
  YM.LIMIT.PRODUCT = YM.LIMIT.ID
  YCOUNT.RPL = COUNT(YM.LIMIT.PRODUCT,@VM)+1
  FOR YAV.RPL = 1 TO YCOUNT.RPL
    YCOUNT.AS.RPL = COUNT(YM.LIMIT.PRODUCT<1,YAV.RPL>,@SM)+1
    FOR YAS.RPL = 1 TO YCOUNT.AS.RPL
      IF YM.LIMIT.PRODUCT<1,YAV.RPL,YAS.RPL> <> "" THEN
        YCOMP = "LIMIT_86_":YM.LIMIT.PRODUCT<1,YAV.RPL,YAS.RPL>
        YFORFIL = YF.LIMIT
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.LIMIT.PRODUCT<1,YAV.RPL,YAS.RPL> = YFOR.FD
      END
    NEXT YAS.RPL
  NEXT YAV.RPL
  YM.LIMIT.REFERENCE = YM.LIMIT.PRODUCT
  YCOUNT.RPL = COUNT(YM.LIMIT.REFERENCE,@VM)+1
  FOR YAV.RPL = 1 TO YCOUNT.RPL
    YCOUNT.AS.RPL = COUNT(YM.LIMIT.REFERENCE<1,YAV.RPL>,@SM)+1
    FOR YAS.RPL = 1 TO YCOUNT.AS.RPL
      IF YM.LIMIT.REFERENCE<1,YAV.RPL,YAS.RPL> <> "" THEN
        YCOMP = "LIMIT.REFERENCE_2_":YM.LIMIT.REFERENCE<1,YAV.RPL,YAS.RPL>
        YFORFIL = YF.LIMIT.REFERENCE
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 1; GOSUB 9000000
        YM.LIMIT.REFERENCE<1,YAV.RPL,YAS.RPL> = YFOR.FD
      END
    NEXT YAS.RPL
  NEXT YAV.RPL
  YR.REC(118) = YM.LIMIT.REFERENCE
  YM.LIMIT.CURRENCY = YM.LIMIT.ID
  YCOUNT.RPL = COUNT(YM.LIMIT.CURRENCY,@VM)+1
  FOR YAV.RPL = 1 TO YCOUNT.RPL
    YCOUNT.AS.RPL = COUNT(YM.LIMIT.CURRENCY<1,YAV.RPL>,@SM)+1
    FOR YAS.RPL = 1 TO YCOUNT.AS.RPL
      IF YM.LIMIT.CURRENCY<1,YAV.RPL,YAS.RPL> <> "" THEN
        YCOMP = "LIMIT_1_":YM.LIMIT.CURRENCY<1,YAV.RPL,YAS.RPL>
        YFORFIL = YF.LIMIT
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.LIMIT.CURRENCY<1,YAV.RPL,YAS.RPL> = YFOR.FD
      END
    NEXT YAS.RPL
  NEXT YAV.RPL
  YM.ARG.P1 = YM.LIMIT.CURRENCY
  YM437.GOSUB = YM.ARG.P1
  YM.LIMIT.21 = YM.LIMIT.ID
  YCOUNT.RPL = COUNT(YM.LIMIT.21,@VM)+1
  FOR YAV.RPL = 1 TO YCOUNT.RPL
    YCOUNT.AS.RPL = COUNT(YM.LIMIT.21<1,YAV.RPL>,@SM)+1
    FOR YAS.RPL = 1 TO YCOUNT.AS.RPL
      IF YM.LIMIT.21<1,YAV.RPL,YAS.RPL> <> "" THEN
        YCOMP = "LIMIT_26_":YM.LIMIT.21<1,YAV.RPL,YAS.RPL>
        YFORFIL = YF.LIMIT
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.LIMIT.21<1,YAV.RPL,YAS.RPL> = YFOR.FD
      END
    NEXT YAS.RPL
  NEXT YAV.RPL
  YM.ARG.P2 = YM.LIMIT.21
  YM438.GOSUB = YM.ARG.P2
  YM.ARG.P3 = YM.CURRENCY
  YM439.GOSUB = YM.ARG.P3
  YM.ARG.P4 = ""
  YM440.GOSUB = YM.ARG.P4
  CALL @RG.S.XCURRENCY (YM437.GOSUB, YM438.GOSUB, YM439.GOSUB, YM440.GOSUB)
  YM.ARG.P1 = YM437.GOSUB
  YM.ARG.P2 = YM438.GOSUB
  YM.ARG.P3 = YM439.GOSUB
  YM.ARG.P4 = YM440.GOSUB
  YM.MAXIMUM.TOTAL = YM.ARG.P4
  YR.REC(119) = YM.MAXIMUM.TOTAL
  YM.ARG.Q1 = YM.LIMIT.CURRENCY
  YM443.GOSUB = YM.ARG.Q1
  YM.LIMIT.27 = YM.LIMIT.ID
  YCOUNT.RPL = COUNT(YM.LIMIT.27,@VM)+1
  FOR YAV.RPL = 1 TO YCOUNT.RPL
    YCOUNT.AS.RPL = COUNT(YM.LIMIT.27<1,YAV.RPL>,@SM)+1
    FOR YAS.RPL = 1 TO YCOUNT.AS.RPL
      IF YM.LIMIT.27<1,YAV.RPL,YAS.RPL> <> "" THEN
        YCOMP = "LIMIT_32.1_":YM.LIMIT.27<1,YAV.RPL,YAS.RPL>
        YFORFIL = YF.LIMIT
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.LIMIT.27<1,YAV.RPL,YAS.RPL> = YFOR.FD
      END
    NEXT YAS.RPL
  NEXT YAV.RPL
  YM.ARG.Q2 = YM.LIMIT.27
  YM444.GOSUB = YM.ARG.Q2
  YM.ARG.Q3 = YM.CURRENCY
  YM445.GOSUB = YM.ARG.Q3
  YM.ARG.Q4 = ""
  YM446.GOSUB = YM.ARG.Q4
  CALL @RG.S.XCURRENCY (YM443.GOSUB, YM444.GOSUB, YM445.GOSUB, YM446.GOSUB)
  YM.ARG.Q1 = YM443.GOSUB
  YM.ARG.Q2 = YM444.GOSUB
  YM.ARG.Q3 = YM445.GOSUB
  YM.ARG.Q4 = YM446.GOSUB
  YM.ONLINE.LIMIT = YM.ARG.Q4
  YR.REC(120) = YM.ONLINE.LIMIT
  YM.ARG.R1 = YM.LIMIT.CURRENCY
  YM452.GOSUB = YM.ARG.R1
  YM.LIMIT.31 = YM.LIMIT.ID
  YCOUNT.RPL = COUNT(YM.LIMIT.31,@VM)+1
  FOR YAV.RPL = 1 TO YCOUNT.RPL
    YCOUNT.AS.RPL = COUNT(YM.LIMIT.31<1,YAV.RPL>,@SM)+1
    FOR YAS.RPL = 1 TO YCOUNT.AS.RPL
      IF YM.LIMIT.31<1,YAV.RPL,YAS.RPL> <> "" THEN
        YCOMP = "LIMIT_36.1_":YM.LIMIT.31<1,YAV.RPL,YAS.RPL>
        YFORFIL = YF.LIMIT
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.LIMIT.31<1,YAV.RPL,YAS.RPL> = YFOR.FD
      END
    NEXT YAS.RPL
  NEXT YAV.RPL
  YM.LIMIT.31A = YM.LIMIT.31
  YM1.LIMIT.31A = YM.LIMIT.31A
  YM.ARG.Q1A = YM.LIMIT.ID
  YM448.GOSUB = YM.ARG.Q1A
  YM.ARG.Q2A = ""
  YM449.GOSUB = YM.ARG.Q2A
  CALL @RG.S.LIMIT.ACCOUNT.OS (YM448.GOSUB, YM449.GOSUB)
  YM.ARG.Q1A = YM448.GOSUB
  YM.ARG.Q2A = YM449.GOSUB
  YM.LIMIT.31A = YM.ARG.Q2A
  YCOUNT.MOD = COUNT(YM1.LIMIT.31A,@VM)+1
  YCOUNT.MOD2 = COUNT(YM.LIMIT.31A,@VM)+1
  IF YCOUNT.MOD2 > YCOUNT.MOD THEN YCOUNT.MOD = YCOUNT.MOD2
  FOR YAV.MOD = 1 TO YCOUNT.MOD
    YCOUNT.AS.MOD = COUNT(YM1.LIMIT.31A<1,YAV.MOD>,@SM)+1
    YCOUNT.AS.MOD2 = COUNT(YM.LIMIT.31A<1,YAV.MOD>,@SM)+1
    IF YCOUNT.AS.MOD2 > YCOUNT.AS.MOD THEN YCOUNT.AS.MOD = YCOUNT.AS.MOD2
    FOR YAS.MOD = 1 TO YCOUNT.AS.MOD
      YFD = YM.LIMIT.31A<1,YAV.MOD,YAS.MOD>
      IF NUM(YM1.LIMIT.31A<1,YAV.MOD,YAS.MOD>) = NUMERIC THEN IF NUM(YFD) = NUMERIC THEN
        YM1.LIMIT.31A<1,YAV.MOD,YAS.MOD> = YM1.LIMIT.31A<1,YAV.MOD,YAS.MOD> + YFD
        IF YM1.LIMIT.31A<1,YAV.MOD,YAS.MOD> = 0 THEN YM1.LIMIT.31A<1,YAV.MOD,YAS.MOD> = ""
      END
    NEXT YAS.MOD
  NEXT YAV.MOD
  YM.LIMIT.31A = YM1.LIMIT.31A
  YM.ARG.R2 = YM.LIMIT.31A
  YM453.GOSUB = YM.ARG.R2
  YM.ARG.R3 = YM.CURRENCY
  YM454.GOSUB = YM.ARG.R3
  YM.ARG.R4 = ""
  YM455.GOSUB = YM.ARG.R4
  CALL @RG.S.XCURRENCY (YM452.GOSUB, YM453.GOSUB, YM454.GOSUB, YM455.GOSUB)
  YM.ARG.R1 = YM452.GOSUB
  YM.ARG.R2 = YM453.GOSUB
  YM.ARG.R3 = YM454.GOSUB
  YM.ARG.R4 = YM455.GOSUB
  YM.TOTAL.OS = YM.ARG.R4
  YR.REC(121) = YM.TOTAL.OS
  YM.ARG.S1 = YM.LIMIT.CURRENCY
  YM459.GOSUB = YM.ARG.S1
  YM.LIMIT.32 = YM.LIMIT.ID
  YCOUNT.RPL = COUNT(YM.LIMIT.32,@VM)+1
  FOR YAV.RPL = 1 TO YCOUNT.RPL
    YCOUNT.AS.RPL = COUNT(YM.LIMIT.32<1,YAV.RPL>,@SM)+1
    FOR YAS.RPL = 1 TO YCOUNT.AS.RPL
      IF YM.LIMIT.32<1,YAV.RPL,YAS.RPL> <> "" THEN
        YCOMP = "LIMIT_37.1_":YM.LIMIT.32<1,YAV.RPL,YAS.RPL>
        YFORFIL = YF.LIMIT
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.LIMIT.32<1,YAV.RPL,YAS.RPL> = YFOR.FD
      END
    NEXT YAS.RPL
  NEXT YAV.RPL
  YM.LIMIT.32A = YM.LIMIT.32
  YM1.LIMIT.32A = YM.LIMIT.32A
  YM.LIMIT.32A = YM.ARG.Q2A
  YCOUNT.MOD = COUNT(YM1.LIMIT.32A,@VM)+1
  YCOUNT.MOD2 = COUNT(YM.LIMIT.32A,@VM)+1
  IF YCOUNT.MOD2 > YCOUNT.MOD THEN YCOUNT.MOD = YCOUNT.MOD2
  FOR YAV.MOD = 1 TO YCOUNT.MOD
    YCOUNT.AS.MOD = COUNT(YM1.LIMIT.32A<1,YAV.MOD>,@SM)+1
    YCOUNT.AS.MOD2 = COUNT(YM.LIMIT.32A<1,YAV.MOD>,@SM)+1
    IF YCOUNT.AS.MOD2 > YCOUNT.AS.MOD THEN YCOUNT.AS.MOD = YCOUNT.AS.MOD2
    FOR YAS.MOD = 1 TO YCOUNT.AS.MOD
      YFD = YM.LIMIT.32A<1,YAV.MOD,YAS.MOD>
      IF NUM(YM1.LIMIT.32A<1,YAV.MOD,YAS.MOD>) = NUMERIC THEN IF NUM(YFD) = NUMERIC THEN
        YM1.LIMIT.32A<1,YAV.MOD,YAS.MOD> = YM1.LIMIT.32A<1,YAV.MOD,YAS.MOD> + YFD
        IF YM1.LIMIT.32A<1,YAV.MOD,YAS.MOD> = 0 THEN YM1.LIMIT.32A<1,YAV.MOD,YAS.MOD> = ""
      END
    NEXT YAS.MOD
  NEXT YAV.MOD
  YM.LIMIT.32A = YM1.LIMIT.32A
  YM.ARG.S2 = YM.LIMIT.32A
  YM460.GOSUB = YM.ARG.S2
  YM.ARG.S3 = YM.CURRENCY
  YM461.GOSUB = YM.ARG.S3
  YM.ARG.S4 = ""
  YM462.GOSUB = YM.ARG.S4
  CALL @RG.S.XCURRENCY (YM459.GOSUB, YM460.GOSUB, YM461.GOSUB, YM462.GOSUB)
  YM.ARG.S1 = YM459.GOSUB
  YM.ARG.S2 = YM460.GOSUB
  YM.ARG.S3 = YM461.GOSUB
  YM.ARG.S4 = YM462.GOSUB
  YM.AVAIL.AMT = YM.ARG.S4
  YR.REC(122) = YM.AVAIL.AMT
  YM.ARG.W1 = YM.LIMIT.CURRENCY
  YM475.GOSUB = YM.ARG.W1
  YM.ARG.T1 = YM.LIMIT.31A
  YM464.GOSUB = YM.ARG.T1
  YM.ARG.T2 = "-1"
  YM465.GOSUB = YM.ARG.T2
  YM.ARG.T3 = ""
  YM466.GOSUB = YM.ARG.T3
  CALL @RG.S.MULTIPLY (YM464.GOSUB, YM465.GOSUB, YM466.GOSUB)
  YM.ARG.T1 = YM464.GOSUB
  YM.ARG.T2 = YM465.GOSUB
  YM.ARG.T3 = YM466.GOSUB
  YM.ARG.U1 = YM.ARG.T3
  YM467.GOSUB = YM.ARG.U1
  YM.ARG.U2 = YM.LIMIT.27
  YM468.GOSUB = YM.ARG.U2
  YM.ARG.U3 = ""
  YM469.GOSUB = YM.ARG.U3
  CALL @RG.S.HIGHEST (YM467.GOSUB, YM468.GOSUB, YM469.GOSUB)
  YM.ARG.U1 = YM467.GOSUB
  YM.ARG.U2 = YM468.GOSUB
  YM.ARG.U3 = YM469.GOSUB
  YM.TEMP.1 = YM.ARG.U3
  YM1.TEMP.1 = YM.TEMP.1
  YM.ARG.V1 = YM.LIMIT.ID
  YM470.GOSUB = YM.ARG.V1
  YM.ARG.V2 = "LIMIT"
  YM471.GOSUB = YM.ARG.V2
  YM.ARG.V3 = "24"
  YM472.GOSUB = YM.ARG.V3
  YM.ARG.V4 = ""
  YM473.GOSUB = YM.ARG.V4
  CALL @RG.S.REPLACE.SUM (YM470.GOSUB, YM471.GOSUB, YM472.GOSUB, YM473.GOSUB)
  YM.ARG.V1 = YM470.GOSUB
  YM.ARG.V2 = YM471.GOSUB
  YM.ARG.V3 = YM472.GOSUB
  YM.ARG.V4 = YM473.GOSUB
  YM.TEMP.1 = YM.ARG.V4
  YCOUNT.MOD = COUNT(YM1.TEMP.1,@VM)+1
  YCOUNT.MOD2 = COUNT(YM.TEMP.1,@VM)+1
  IF YCOUNT.MOD2 > YCOUNT.MOD THEN YCOUNT.MOD = YCOUNT.MOD2
  FOR YAV.MOD = 1 TO YCOUNT.MOD
    YCOUNT.AS.MOD = COUNT(YM1.TEMP.1<1,YAV.MOD>,@SM)+1
    YCOUNT.AS.MOD2 = COUNT(YM.TEMP.1<1,YAV.MOD>,@SM)+1
    IF YCOUNT.AS.MOD2 > YCOUNT.AS.MOD THEN YCOUNT.AS.MOD = YCOUNT.AS.MOD2
    FOR YAS.MOD = 1 TO YCOUNT.AS.MOD
      YFD = YM.TEMP.1<1,YAV.MOD,YAS.MOD>
      IF NUM(YM1.TEMP.1<1,YAV.MOD,YAS.MOD>) = NUMERIC THEN IF NUM(YFD) = NUMERIC THEN
        YM1.TEMP.1<1,YAV.MOD,YAS.MOD> = YM1.TEMP.1<1,YAV.MOD,YAS.MOD> - YFD
        IF YM1.TEMP.1<1,YAV.MOD,YAS.MOD> = 0 THEN YM1.TEMP.1<1,YAV.MOD,YAS.MOD> = ""
      END
    NEXT YAS.MOD
  NEXT YAV.MOD
  YM.TEMP.1 = YM1.TEMP.1
  YM.ARG.W2 = YM.TEMP.1
  YM476.GOSUB = YM.ARG.W2
  YM.ARG.W3 = YM.CURRENCY
  YM477.GOSUB = YM.ARG.W3
  YM.ARG.W4 = ""
  YM478.GOSUB = YM.ARG.W4
  CALL @RG.S.XCURRENCY (YM475.GOSUB, YM476.GOSUB, YM477.GOSUB, YM478.GOSUB)
  YM.ARG.W1 = YM475.GOSUB
  YM.ARG.W2 = YM476.GOSUB
  YM.ARG.W3 = YM477.GOSUB
  YM.ARG.W4 = YM478.GOSUB
  YM.UNSECURED.AMOUNT = YM.ARG.W4
  YR.REC(123) = YM.UNSECURED.AMOUNT
  YM.ARG.X1 = YM.LIMIT.ID
  YM480.GOSUB = YM.ARG.X1
  YM.ARG.X2 = ""
  YM481.GOSUB = YM.ARG.X2
  CALL @RG.S.LIMIT.COLLAT.RIGHT (YM480.GOSUB, YM481.GOSUB)
  YM.ARG.X1 = YM480.GOSUB
  YM.ARG.X2 = YM481.GOSUB
  YM.COLLATERAL.RIGHT.ID = YM.ARG.X2
  YM.COLLATERAL.CODE = YM.COLLATERAL.RIGHT.ID
  YCOUNT.RPL = COUNT(YM.COLLATERAL.CODE,@VM)+1
  FOR YAV.RPL = 1 TO YCOUNT.RPL
    YCOUNT.AS.RPL = COUNT(YM.COLLATERAL.CODE<1,YAV.RPL>,@SM)+1
    FOR YAS.RPL = 1 TO YCOUNT.AS.RPL
      IF YM.COLLATERAL.CODE<1,YAV.RPL,YAS.RPL> <> "" THEN
        YCOMP = "COLLATERAL.RIGHT_1_":YM.COLLATERAL.CODE<1,YAV.RPL,YAS.RPL>
        YFORFIL = YF.COLLATERAL.RIGHT
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.COLLATERAL.CODE<1,YAV.RPL,YAS.RPL> = YFOR.FD
      END
    NEXT YAS.RPL
  NEXT YAV.RPL
  YM.COLLATERAL.DESC = YM.COLLATERAL.CODE
  YCOUNT.RPL = COUNT(YM.COLLATERAL.DESC,@VM)+1
  FOR YAV.RPL = 1 TO YCOUNT.RPL
    YCOUNT.AS.RPL = COUNT(YM.COLLATERAL.DESC<1,YAV.RPL>,@SM)+1
    FOR YAS.RPL = 1 TO YCOUNT.AS.RPL
      IF YM.COLLATERAL.DESC<1,YAV.RPL,YAS.RPL> <> "" THEN
        YCOMP = "COLLATERAL.CODE_1_":YM.COLLATERAL.DESC<1,YAV.RPL,YAS.RPL>
        YFORFIL = YF.COLLATERAL.CODE
        YPART.S = ""; YFD.LEN = ""; YHANDLE.LNGG = 0; GOSUB 9000000
        YM.COLLATERAL.DESC<1,YAV.RPL,YAS.RPL> = YFOR.FD
      END
    NEXT YAS.RPL
  NEXT YAV.RPL
  YR.REC(124) = YM.COLLATERAL.DESC
  YM.ARG.Z1 = YM.LIMIT.CURRENCY
  YM487.GOSUB = YM.ARG.Z1
  YM.ARG.Y1 = YM.LIMIT.ID
  YM485.GOSUB = YM.ARG.Y1
  YM.ARG.Y2 = ""
  YM486.GOSUB = YM.ARG.Y2
  CALL @RG.S.LIMIT.SECURED.AMT (YM485.GOSUB, YM486.GOSUB)
  YM.ARG.Y1 = YM485.GOSUB
  YM.ARG.Y2 = YM486.GOSUB
  YM.ARG.Z2 = YM.ARG.Y2
  YM488.GOSUB = YM.ARG.Z2
  YM.ARG.Z3 = YM.CURRENCY
  YM489.GOSUB = YM.ARG.Z3
  YM.ARG.Z4 = ""
  YM490.GOSUB = YM.ARG.Z4
  CALL @RG.S.XCURRENCY (YM487.GOSUB, YM488.GOSUB, YM489.GOSUB, YM490.GOSUB)
  YM.ARG.Z1 = YM487.GOSUB
  YM.ARG.Z2 = YM488.GOSUB
  YM.ARG.Z3 = YM489.GOSUB
  YM.ARG.Z4 = YM490.GOSUB
  YM.SECURED.AMT = YM.ARG.Z4
  YR.REC(125) = YM.SECURED.AMT
  YM.COLUMN.1 = YM.MAXIMUM.TOTAL
  YM492.GOSUB = YM.COLUMN.1
  YM.TOTAL.1 = ""
  YM493.GOSUB = YM.TOTAL.1
  CALL @RG.S.SUM (YM492.GOSUB, YM493.GOSUB)
  YM.COLUMN.1 = YM492.GOSUB
  YM.TOTAL.1 = YM493.GOSUB
  YR.REC(126) = YM.TOTAL.1
  YM.COLUMN.2 = YM.ONLINE.LIMIT
  YM494.GOSUB = YM.COLUMN.2
  YM.TOTAL.2 = ""
  YM495.GOSUB = YM.TOTAL.2
  CALL @RG.S.SUM (YM494.GOSUB, YM495.GOSUB)
  YM.COLUMN.2 = YM494.GOSUB
  YM.TOTAL.2 = YM495.GOSUB
  YR.REC(127) = YM.TOTAL.2
  YM.COLUMN.3 = YM.TOTAL.OS
  YM496.GOSUB = YM.COLUMN.3
  YM.TOTAL.3 = ""
  YM497.GOSUB = YM.TOTAL.3
  CALL @RG.S.SUM (YM496.GOSUB, YM497.GOSUB)
  YM.COLUMN.3 = YM496.GOSUB
  YM.TOTAL.3 = YM497.GOSUB
  YR.REC(128) = YM.TOTAL.3
  YM.COLUMN.4 = YM.AVAIL.AMT
  YM498.GOSUB = YM.COLUMN.4
  YM.TOTAL.4 = ""
  YM499.GOSUB = YM.TOTAL.4
  CALL @RG.S.SUM (YM498.GOSUB, YM499.GOSUB)
  YM.COLUMN.4 = YM498.GOSUB
  YM.TOTAL.4 = YM499.GOSUB
  YR.REC(129) = YM.TOTAL.4
  YM.COLUMN.5 = YM.UNSECURED.AMOUNT
  YM500.GOSUB = YM.COLUMN.5
  YM.TOTAL.5 = ""
  YM501.GOSUB = YM.TOTAL.5
  CALL @RG.S.SUM (YM500.GOSUB, YM501.GOSUB)
  YM.COLUMN.5 = YM500.GOSUB
  YM.TOTAL.5 = YM501.GOSUB
  YR.REC(130) = YM.TOTAL.5
  YM.COLUMN.6A = YM.SECURED.AMT
  YM502.GOSUB = YM.COLUMN.6A
  YM.TOTAL.6A = ""
  YM503.GOSUB = YM.TOTAL.6A
  CALL @RG.S.SUM (YM502.GOSUB, YM503.GOSUB)
  YM.COLUMN.6A = YM502.GOSUB
  YM.TOTAL.6A = YM503.GOSUB
  YM.TEMP.2 = YM.TOTAL.6A
  YM.COLUMN.6B = YM.TEMP.2
  YM505.GOSUB = YM.COLUMN.6B
  YM.TOTAL.6B = ""
  YM506.GOSUB = YM.TOTAL.6B
  CALL @RG.S.SUM (YM505.GOSUB, YM506.GOSUB)
  YM.COLUMN.6B = YM505.GOSUB
  YM.TOTAL.6B = YM506.GOSUB
  YR.REC(131) = YM.TOTAL.6B
  YM.TOTAL.MARGIN = YM.TOTAL.UNPLEDGED
  YM1.TOTAL.MARGIN = YM.TOTAL.MARGIN
  YM.TOTAL.MARGIN = YM.TOTAL.PLEDGED
  IF NUM(YM1.TOTAL.MARGIN) = NUMERIC THEN IF NUM(YM.TOTAL.MARGIN) = NUMERIC THEN
    YM1.TOTAL.MARGIN = YM1.TOTAL.MARGIN + YM.TOTAL.MARGIN
    IF YM1.TOTAL.MARGIN = 0 THEN YM1.TOTAL.MARGIN = ""
  END
  YM.TOTAL.MARGIN = YM1.TOTAL.MARGIN
  YM.CALC.1 = YM.TOTAL.MARGIN
  YM1.CALC.1 = YM.CALC.1
  YM.CALC.1 = YM.TOTAL.1
  IF NUM(YM1.CALC.1) = NUMERIC THEN IF NUM(YM.CALC.1) = NUMERIC THEN
    YM1.CALC.1 = YM1.CALC.1 - YM.CALC.1
    IF YM1.CALC.1 = 0 THEN YM1.CALC.1 = ""
  END
  YM.CALC.1 = YM1.CALC.1
  YR.REC(132) = YM.CALC.1
  YM.CALC.2 = YM.TOTAL.MARGIN
  YM1.CALC.2 = YM.CALC.2
  YM.CALC.2 = YM.TOTAL.2
  IF NUM(YM1.CALC.2) = NUMERIC THEN IF NUM(YM.CALC.2) = NUMERIC THEN
    YM1.CALC.2 = YM1.CALC.2 - YM.CALC.2
    IF YM1.CALC.2 = 0 THEN YM1.CALC.2 = ""
  END
  YM.CALC.2 = YM1.CALC.2
  YR.REC(133) = YM.CALC.2
  YM.CALC.3 = YM.TOTAL.MARGIN
  YM1.CALC.3 = YM.CALC.3
  YM.CALC.3 = YM.TOTAL.3
  IF NUM(YM1.CALC.3) = NUMERIC THEN IF NUM(YM.CALC.3) = NUMERIC THEN
    YM1.CALC.3 = YM1.CALC.3 - YM.CALC.3
    IF YM1.CALC.3 = 0 THEN YM1.CALC.3 = ""
  END
  YM.CALC.3 = YM1.CALC.3
  YR.REC(134) = YM.CALC.3
*
  YKEYNO = YKEYNO + 1
  IF YKEYNO > 9999 THEN
    YKEY = YKEY:YKEYNO
  END ELSE
    YKEY = YKEY : FMT(YKEYNO,'5"0"R')
  END
  MATWRITE YR.REC TO F.FILE, YKEY
*
  IF NOT(PHNO) THEN
    IF YWRITNO < 9 THEN
      YWRITNO = YWRITNO + 1
    END ELSE
      YWRITNO = 0; YBLOCKNO = YBLOCKNO + 10
      PRINT @(41,L1ST-3):YBLOCKNO+YWRITNO:
    END
  END
  RETURN
*************************************************************************
*
* Update Key (and convert invalid Key char.)
8000000:
*
  YLEN.KEY = LEN(YKEYFD)
  FOR YNO = 1 TO YLEN.KEY
    YKEY.CHR = YKEYFD[YNO,1]
   IF YKEY.CHR MATCHES "1A" OR YKEY.CHR MATCHES "1N" THEN
        YKEY = YKEY : YKEY.CHR
   END ELSE
        IF INDEX(".$",YKEY.CHR,1) THEN
          YKEY = YKEY : YKEY.CHR
        END ELSE
          YKEY = YKEY : "&"
        END
   END
  NEXT YNO
  RETURN
*************************************************************************
*
* Update table of Parameters of foreign file
9000000:
*
  LOCATE YCOMP IN YT.FORFIL<1,1> SETTING YLOC.FOR ELSE
    YFOR.ID = FIELD(YCOMP,"_",3)
    YFOR.FD = FIELD(YCOMP,"_",2)
    YFOR.AF = FIELD(YFOR.FD,".",1)
    YFOR.AV = FIELD(YFOR.FD,".",2)
    YFOR.AS = FIELD(YFOR.FD,".",3)
*
    T.PWD.SAVE = T.PWD; T.PWD = ""
    IF YT.SMS THEN
      LOCATE FIELD(YCOMP,"_",1) IN YT.SMS<1,1> SETTING T.PWD ELSE NULL
    END
    IF T.PWD THEN
      MAT R.NEW.LAST = MAT R.NEW
      ID.NEW.SAVE = ID.NEW; ID.NEW = YFOR.ID
      MATREAD R.NEW FROM YFORFIL, ID.NEW ELSE MAT R.NEW = ""
      T.PWD = YT.SMS<2,T.PWD>; CONVERT @SM TO @FM IN T.PWD
      CALL CONTROL.USER.PROFILE ("RECORD")
      IF ETEXT THEN
        YFOR.FD = "@"
      END ELSE
        YFOR.FD = R.NEW(YFOR.AF)
      END
      MAT R.NEW = MAT R.NEW.LAST; ID.NEW = ID.NEW.SAVE
    END ELSE
     IF FIELD(YCOMP,"_",1) = "DATES"  AND (RUNNING.UNDER.BATCH) THEN
        COB.N.W.DATE = R.DATES(YFOR.AF)
        YFOR.FD = COB.N.W.DATE
     END ELSE
        READV YFOR.FD FROM YFORFIL, YFOR.ID, YFOR.AF ELSE YFOR.FD = ""
     END
    END
    T.PWD = T.PWD.SAVE; T.PWD.SAVE = ""
*
    IF NOT(YHANDLE.LNGG) THEN
      IF YFOR.AV <> "" THEN YFOR.FD = YFOR.FD<1,YFOR.AV,YFOR.AS>
    END ELSE
      IF YFOR.FD<1,LNGG> = "" THEN
        YFOR.FD = YFOR.FD<1,1>
      END ELSE
        YFOR.FD = YFOR.FD<1,LNGG>
      END
    END
    IF NOT(COUNT(YFOR.FD,@VM)) THEN
      DEL YT.FORFIL<1,50>; DEL YT.FORFIL<2,50>
      INS YCOMP BEFORE YT.FORFIL<1,1>
      INS YFOR.FD BEFORE YT.FORFIL<2,1>
    END
    YLOC.FOR = 0
  END
  IF YLOC.FOR THEN YFOR.FD = YT.FORFIL<2,YLOC.FOR>
  IF YPART.S <> "" THEN
    YCOUNT.FOR = COUNT(YFOR.FD,@VM)+1
    FOR YAV.FOR = 1 TO YCOUNT.FOR
      YCOUNT.AS.FOR = COUNT(YFOR.FD<1,YAV.FOR>,@SM)+1
      FOR YAS.FOR = 1 TO YCOUNT.AS.FOR
        IF YFD.LEN = "" THEN
          YFOR.FD<1,YAV.FOR,YAS.FOR> = FIELD(YFOR.FD<1,YAV.FOR,YAS.FOR>,YPART.S,YPART.L)
        END ELSE
          X = FMT(YFOR.FD<1,YAV.FOR,YAS.FOR>,YFD.LEN)
          YFOR.FD<1,YAV.FOR,YAS.FOR> = X[YPART.S,YPART.L]
        END
      NEXT YAS.FOR
    NEXT YAV.FOR
  END
  RETURN
*************************************************************************
*
* Ask for valid file password in connection with Company code
9300000:
*
  IF X THEN IF R.USER<EB.USE.COMPANY.RESTR,X> THEN
    IF R.USER<EB.USE.COMPANY.RESTR,X> <> YID.COMP THEN X = 0
  END
  RETURN
*************************************************************************
END
