*
*-----------------------------------------------------------------------------
*-----------------------------------------------------------------------------
SUBROUTINE DR.REGN22.RCL.SEC.TRD.AMT.VAL
    $INSERT I_COMMON
    $INSERT I_EQUATE

    $INSERT I_F.SEC.TRADE
    $INSERT I_F.SECURITY.MASTER

    FN.SEC.TRADE = 'F.SEC.TRADE'
    F.SEC.TRADE = ''
    CALL OPF(FN.SEC.TRADE,F.SEC.TRADE)
    R.SEC.TRADE = ''
    CALL F.READ(FN.SEC.TRADE,COMI,R.SEC.TRADE,F.SEC.TRADE,SEC.TRADE.ERR)
    SEC.MASTER.ID = R.SEC.TRADE<SC.SBS.SECURITY.CODE>
    FN.SECURITY.MASTER = 'F.SECURITY.MASTER'
    F.SECURITY.MASTER = ''
    CALL OPF(FN.SECURITY.MASTER,F.SECURITY.MASTER)
    R.SECURITY.MASTER = ''
    CALL F.READ(FN.SECURITY.MASTER,SEC.MASTER.ID,R.SECURITY.MASTER,F.SECURITY.MASTER,SECURITY.MASTER.ERR)
    NOMINAL.VAL = (R.SECURITY.MASTER<SC.SCM.TRADING.UNITS> * R.SECURITY.MASTER<SC.SCM.LAST.PRICE>)/100
    COMI = NOMINAL.VAL
RETURN

END
