SUBROUTINE REDO.B.INCREASE.AGENT

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.TSA.SERVICE
    $INSERT I_F.TSA.WORKLOAD.PROFILE

    FN.TSA = 'F.TSA.SERVICE'
    F.TSA = ''
    CALL OPF(FN.TSA,F.TSA)

    FN.TWF = 'F.TSA.WORKLOAD.PROFILE'
    F.TWF = ''
    CALL OPF(FN.TWF,F.TWFF.TWF)

    FN.REDO.STR.TSA.AGENT = 'F.REDO.STR.TSA.AGENT'
    F.REDO.STR.TSA.AGENT = ''
    CALL OPF(FN.REDO.STR.TSA.AGENT,F.REDO.STR.TSA.AGENT)

    Y.ID = 'COB'
    CALL F.READ(FN.TSA,Y.ID,R.TSA,F.TSA,TS.ERR)

    Y.TWF = R.TSA<TS.TSM.WORK.PROFILE>

    CALL F.READ(FN.REDO.STR.TSA.AGENT,Y.TWF,R.STR.TS,F.REDO.STR.TSA.AGENT,ERR.STR)

    IF R.STR.TS THEN
        Y.AGENTS = R.STR.TS

        CALL F.READ(FN.TWF,Y.TWF,R.TWF,F.TWF,TWF.ER)
        R.TWF<TS.WLP.AGENTS.REQUIRED> = Y.AGENTS

        CALL F.WRITE(FN.TWF,Y.TWF,R.TWF)

        R.TSA<TS.TSM.SERVER.NAME> = ''

        CALL F.WRITE(FN.TSA,Y.ID,R.TSA)

        CALL F.DELETE(FN.REDO.STR.TSA.AGENT,Y.TWF)
    END

END
