SUBROUTINE REDO.B.EXT.SUNN.CUS.STATUS.LOAD

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_REDO.B.EXT.SUNN.COMMON

    FN.REDO.STORE.SUNN.CUS.ST = 'F.REDO.STORE.SUNN.CUS.ST'
    F.REDO.STORE.SUNN.CUS.ST = ''
    CALL OPF(FN.REDO.STORE.SUNN.CUS.ST,F.REDO.STORE.SUNN.CUS.ST)

    FN.REDO.INTERFACE.PARAM = 'F.REDO.INTERFACE.PARAM'
    F.REDO.INTERFACE.PARAM = ''
    CALL OPF(FN.REDO.INTERFACE.PARAM,F.REDO.INTERFACE.PARAM)

RETURN
